version: 1
accounts:
  - name: alice
    coins:
      - 2000000000alpha
  - name: bob
    coins:
      - 10000alpha
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 1000alpha
validators:
  - name: alice
    bonded: 2000000alpha
genesis:
  app_state:
    staking:
      params:
        bond_denom: "alpha"