version: 1
accounts:
  - name: alice
    coins:
      - 2000000alpha
  - name: bob
    coins:
      - 100alpha
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 100alpha
validators:
  - name: alice
    bonded: 1000000alpha
genesis:
  chain_id: "structstestnet-00"
  app_state:
    staking:
      params:
        bond_denom: alpha