version: 1
accounts:
  - name: alice
    coins:
      - 200alpha
  - name: bob
    coins:
      - 100alpha
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 100alpha
validators:
  - name: alice
    bonded: 100alpha
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: "alpha"
    staking:
      params:
        bond_denom: "alpha"
    gov:
      deposit_params:
        min_deposit:
          - amount: "100"
            denom: "alpha"
  chain_id: "structstestnet-00"