version: 1
accounts:
  - name: alice
    coins:
      - 2000000alpha
  - name: bob
    coins:
      - 100alpha
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: "alpha"
    staking:
      params:
        bond_denom: "alpha"
    gov:
      deposit_params:
        min_deposit:
          - amount: "100"
            denom: "alpha"
  chain_id: "structstestnet-00"