// Command maketables emits x/structs/types/unicode_tables.go, the checked-in
// Unicode classification data that governs every consensus-visible name
// decision in the structs module.
//
// Run it through go generate from the types package:
//
//	cd x/structs/types && go generate ./...
//
// It refuses to run on a toolchain whose Unicode tables are not the pinned
// version. That is the whole point of the file: the tables must describe one
// fixed Unicode version rather than whatever the building toolchain happens to
// ship, so regenerating them has to be a deliberate act on a matching
// toolchain and never an accidental side effect of a Go upgrade. Moving the
// pin to a newer Unicode version changes which names the chain accepts and is
// therefore a consensus-breaking change that needs an upgrade handler.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"runtime"
	"unicode"
)

// pinnedVersion is the Unicode version this generator is allowed to read from
// the toolchain. Bumping it means bumping the chain's accepted character set.
const pinnedVersion = "15.0.0"

func main() {
	out := flag.String("out", "unicode_tables.go", "output file")
	check := flag.Bool("check", false,
		"report whether this toolchain still ships the pinned Unicode version and exit")
	flag.Parse()

	if *check {
		fmt.Printf("pinned Unicode version:    %s\ntoolchain Unicode version: %s (%s)\n",
			pinnedVersion, unicode.Version, runtime.Version())
		if unicode.Version == pinnedVersion {
			fmt.Println("match: the exhaustive table-fidelity test can verify the checked-in tables.")
			return
		}
		// Not an error in itself. The checked-in tables are what the binary uses,
		// so consensus is unaffected; what is lost is the test that compares them
		// against the toolchain, which quietly skips from here on.
		fmt.Println("MISMATCH: consensus is unaffected -- the binary uses the checked-in tables --")
		fmt.Println("but TestPinnedTablesMatchToolchain now skips, so the tables are guarded only")
		fmt.Println("by TestPinnedTablesChecksum and the cross-script vectors. Do NOT regenerate to")
		fmt.Println("silence this: that would change the chain's accepted character set.")
		os.Exit(1)
	}

	if unicode.Version != pinnedVersion {
		log.Fatalf("maketables: toolchain ships Unicode %s but the pinned version is %s.\n"+
			"Regenerate with a Go toolchain at Unicode %s, or, if the pin is deliberately moving,\n"+
			"update pinnedVersion here and in x/structs/types/unicode_pinned.go and ship the\n"+
			"change as a consensus-breaking upgrade.",
			unicode.Version, pinnedVersion, pinnedVersion)
	}

	var buf bytes.Buffer
	writeHeader(&buf)
	writeRangeTable(&buf, "pinnedL", "letters (general category L)", unicode.L)
	writeRangeTable(&buf, "pinnedMn", "non-spacing marks (general category Mn)", unicode.Mn)
	writeRangeTable(&buf, "pinnedMe", "enclosing marks (general category Me)", unicode.Me)
	writeRangeTable(&buf, "pinnedCf", "format characters (general category Cf)", unicode.Cf)
	writeRangeTable(&buf, "pinnedWhiteSpace", "the White_Space property", unicode.White_Space)
	writeLowerCaseRanges(&buf)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("maketables: generated source does not parse: %v", err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatalf("maketables: %v", err)
	}
	fmt.Printf("maketables: wrote %s from Unicode %s\n", *out, unicode.Version)
}

func writeHeader(buf *bytes.Buffer) {
	fmt.Fprintf(buf, `// Code generated by internal/maketables; DO NOT EDIT.
//
// Unicode %s classification data, extracted from the standard library of a
// toolchain shipping that exact version. Consensus depends on these tables
// being identical in every binary, which is why they are checked in rather
// than read from the building toolchain. See unicode_pinned.go.

package types

import "unicode"

`, unicode.Version)
}

func writeRangeTable(buf *bytes.Buffer, name, description string, t *unicode.RangeTable) {
	fmt.Fprintf(buf, "// %s is %s.\nvar %s = &unicode.RangeTable{\n", name, description, name)

	if len(t.R16) > 0 {
		fmt.Fprintf(buf, "R16: []unicode.Range16{\n")
		for _, r := range t.R16 {
			fmt.Fprintf(buf, "{0x%04x, 0x%04x, %d},\n", r.Lo, r.Hi, r.Stride)
		}
		fmt.Fprintf(buf, "},\n")
	}
	if len(t.R32) > 0 {
		fmt.Fprintf(buf, "R32: []unicode.Range32{\n")
		for _, r := range t.R32 {
			fmt.Fprintf(buf, "{0x%05x, 0x%05x, %d},\n", r.Lo, r.Hi, r.Stride)
		}
		fmt.Fprintf(buf, "},\n")
	}
	// Copied verbatim rather than recomputed. unicode.Is ignores LatinOffset,
	// but unicode.isExcludingLatin trusts it to skip the Latin-1 prefix of
	// R16, so a table carrying a wrong value would answer incorrectly for
	// every rune above U+00FF the moment anything reached it that way.
	fmt.Fprintf(buf, "LatinOffset: %d,\n}\n\n", t.LatinOffset)
}

// writeLowerCaseRanges emits the simple-lowercase half of unicode.CaseRanges.
//
// Only the LowerCase delta is kept, because that is the only mapping the
// module performs, and ranges whose lowercase mapping is the identity are
// dropped entirely: a rune that misses the binary search is returned
// unchanged, which is exactly what a zero delta would have done. The
// UpperLower sentinel is preserved verbatim since it encodes an alternating
// upper/lower sequence rather than a delta.
func writeLowerCaseRanges(buf *bytes.Buffer) {
	fmt.Fprintf(buf, `// pinnedLowerCaseRanges is the simple-lowercase mapping, sorted by Lo and
// searched by pinnedToLower. Ranges that lowercase to themselves are omitted.
var pinnedLowerCaseRanges = []pinnedCaseRange{
`)

	var kept int
	for _, cr := range unicode.CaseRanges {
		delta := cr.Delta[unicode.LowerCase]
		if delta == 0 {
			continue
		}
		kept++
		if delta > unicode.MaxRune {
			fmt.Fprintf(buf, "{0x%04x, 0x%04x, upperLowerSentinel},\n", cr.Lo, cr.Hi)
			continue
		}
		fmt.Fprintf(buf, "{0x%04x, 0x%04x, %d},\n", cr.Lo, cr.Hi, delta)
	}

	fmt.Fprintf(buf, "}\n\n// %d of %d case ranges carry a non-identity lowercase mapping.\n",
		kept, len(unicode.CaseRanges))
}
