// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: structs/structs/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the structs module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params          Params              `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PortId          string              `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	AllocationList  []Allocation        `protobuf:"bytes,3,rep,name=allocationList,proto3" json:"allocationList"`
	InfusionList    []Infusion          `protobuf:"bytes,4,rep,name=infusionList,proto3" json:"infusionList"`
	GuildList       []Guild             `protobuf:"bytes,6,rep,name=guildList,proto3" json:"guildList"`
	GuildCount      uint64              `protobuf:"varint,7,opt,name=guildCount,proto3" json:"guildCount,omitempty"`
	PlanetList      []Planet            `protobuf:"bytes,8,rep,name=planetList,proto3" json:"planetList"`
	PlanetCount     uint64              `protobuf:"varint,9,opt,name=planetCount,proto3" json:"planetCount,omitempty"`
	PlayerList      []Player            `protobuf:"bytes,10,rep,name=playerList,proto3" json:"playerList"`
	PlayerCount     uint64              `protobuf:"varint,11,opt,name=playerCount,proto3" json:"playerCount,omitempty"`
	ReactorList     []Reactor           `protobuf:"bytes,12,rep,name=reactorList,proto3" json:"reactorList"`
	ReactorCount    uint64              `protobuf:"varint,13,opt,name=reactorCount,proto3" json:"reactorCount,omitempty"`
	StructList      []Struct            `protobuf:"bytes,14,rep,name=structList,proto3" json:"structList"`
	StructCount     uint64              `protobuf:"varint,15,opt,name=structCount,proto3" json:"structCount,omitempty"`
	SubstationList  []Substation        `protobuf:"bytes,16,rep,name=substationList,proto3" json:"substationList"`
	SubstationCount uint64              `protobuf:"varint,17,opt,name=substationCount,proto3" json:"substationCount,omitempty"`
	PermissionList  []*PermissionRecord `protobuf:"bytes,18,rep,name=permissionList,proto3" json:"permissionList,omitempty"`
	GridList        []*GridRecord       `protobuf:"bytes,19,rep,name=gridList,proto3" json:"gridList,omitempty"`
	AddressList     []*AddressRecord    `protobuf:"bytes,20,rep,name=addressList,proto3" json:"addressList,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_39407fc37d8c4705, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *GenesisState) GetAllocationList() []Allocation {
	if m != nil {
		return m.AllocationList
	}
	return nil
}

func (m *GenesisState) GetInfusionList() []Infusion {
	if m != nil {
		return m.InfusionList
	}
	return nil
}

func (m *GenesisState) GetGuildList() []Guild {
	if m != nil {
		return m.GuildList
	}
	return nil
}

func (m *GenesisState) GetGuildCount() uint64 {
	if m != nil {
		return m.GuildCount
	}
	return 0
}

func (m *GenesisState) GetPlanetList() []Planet {
	if m != nil {
		return m.PlanetList
	}
	return nil
}

func (m *GenesisState) GetPlanetCount() uint64 {
	if m != nil {
		return m.PlanetCount
	}
	return 0
}

func (m *GenesisState) GetPlayerList() []Player {
	if m != nil {
		return m.PlayerList
	}
	return nil
}

func (m *GenesisState) GetPlayerCount() uint64 {
	if m != nil {
		return m.PlayerCount
	}
	return 0
}

func (m *GenesisState) GetReactorList() []Reactor {
	if m != nil {
		return m.ReactorList
	}
	return nil
}

func (m *GenesisState) GetReactorCount() uint64 {
	if m != nil {
		return m.ReactorCount
	}
	return 0
}

func (m *GenesisState) GetStructList() []Struct {
	if m != nil {
		return m.StructList
	}
	return nil
}

func (m *GenesisState) GetStructCount() uint64 {
	if m != nil {
		return m.StructCount
	}
	return 0
}

func (m *GenesisState) GetSubstationList() []Substation {
	if m != nil {
		return m.SubstationList
	}
	return nil
}

func (m *GenesisState) GetSubstationCount() uint64 {
	if m != nil {
		return m.SubstationCount
	}
	return 0
}

func (m *GenesisState) GetPermissionList() []*PermissionRecord {
	if m != nil {
		return m.PermissionList
	}
	return nil
}

func (m *GenesisState) GetGridList() []*GridRecord {
	if m != nil {
		return m.GridList
	}
	return nil
}

func (m *GenesisState) GetAddressList() []*AddressRecord {
	if m != nil {
		return m.AddressList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "structs.structs.GenesisState")
}

func init() { proto.RegisterFile("structs/structs/genesis.proto", fileDescriptor_39407fc37d8c4705) }

var fileDescriptor_39407fc37d8c4705 = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xb3, 0xb4, 0x4a, 0x13, 0x27, 0x34, 0xd4, 0x54, 0x24, 0xa4, 0xb0, 0x2c, 0x3d, 0x45,
	0x1c, 0x12, 0x51, 0x0e, 0x48, 0x95, 0x90, 0x20, 0x3d, 0x44, 0x91, 0x38, 0xa0, 0xcd, 0x8d, 0x0b,
	0xda, 0x66, 0x4d, 0xb4, 0x22, 0x59, 0x47, 0xb6, 0x23, 0xb1, 0x6f, 0x81, 0xc4, 0x4b, 0x70, 0xe4,
	0x31, 0x7a, 0xec, 0x91, 0x13, 0x42, 0xc9, 0x81, 0xd7, 0x40, 0x1e, 0xcf, 0xfe, 0xc9, 0x9a, 0xed,
	0x25, 0x8e, 0x67, 0xe6, 0xfb, 0x7e, 0xb6, 0xc7, 0x6b, 0xf2, 0x54, 0x2a, 0xb1, 0x99, 0x2b, 0x39,
	0x4a, 0xc7, 0x05, 0x8b, 0x99, 0x8c, 0xe4, 0x70, 0x2d, 0xb8, 0xe2, 0xb4, 0x83, 0xe1, 0x21, 0x8e,
	0xfd, 0x93, 0x60, 0x15, 0xc5, 0x7c, 0x04, 0xbf, 0xa6, 0xa6, 0x7f, 0xba, 0xe0, 0x0b, 0x0e, 0x7f,
	0x47, 0xfa, 0x1f, 0x46, 0x9f, 0x94, 0x8d, 0xd7, 0x81, 0x08, 0x56, 0xe8, 0xdb, 0xb7, 0xb0, 0x41,
	0x18, 0x0a, 0x26, 0xd3, 0xb4, 0x67, 0xa5, 0x97, 0x4b, 0x3e, 0x0f, 0x54, 0xc4, 0x63, 0xac, 0xe8,
	0x5b, 0xeb, 0x16, 0x51, 0x88, 0xb9, 0x33, 0x2b, 0xb7, 0x89, 0x96, 0x69, 0xd2, 0x2d, 0x27, 0xa3,
	0xf8, 0xf3, 0x46, 0xde, 0x61, 0xfc, 0x85, 0x25, 0x95, 0xcb, 0x5a, 0x33, 0xb1, 0x8a, 0x64, 0x41,
	0x6d, 0xef, 0x7a, 0x19, 0x24, 0x4c, 0xdc, 0x91, 0x8d, 0x99, 0xaa, 0x3a, 0x13, 0xc1, 0x82, 0xb9,
	0xe2, 0x95, 0x62, 0x33, 0x56, 0x2d, 0x4d, 0x6e, 0xae, 0xa5, 0x2a, 0x9c, 0xd8, 0xf9, 0xf7, 0x06,
	0x69, 0x4f, 0x4c, 0x73, 0x67, 0x2a, 0x50, 0x8c, 0x5e, 0x92, 0xba, 0xe9, 0x49, 0xcf, 0xf1, 0x9c,
	0x41, 0xeb, 0xa2, 0x3b, 0x2c, 0x35, 0x7b, 0xf8, 0x01, 0xd2, 0xe3, 0xe6, 0xcd, 0xef, 0x67, 0xb5,
	0x1f, 0x7f, 0x7f, 0xbe, 0x70, 0x7c, 0x54, 0xd0, 0x2e, 0x39, 0x5a, 0x73, 0xa1, 0x3e, 0x45, 0x61,
	0xef, 0x9e, 0xe7, 0x0c, 0x9a, 0x7e, 0x5d, 0x4f, 0xa7, 0x21, 0x9d, 0x92, 0xe3, 0xbc, 0x57, 0xef,
	0x23, 0xa9, 0x7a, 0x07, 0xde, 0xc1, 0xa0, 0x75, 0x71, 0x66, 0x99, 0xbf, 0xcb, 0xca, 0xc6, 0x87,
	0x1a, 0xe0, 0x97, 0x84, 0xf4, 0x8a, 0xb4, 0xd3, 0xde, 0x80, 0xd1, 0x21, 0x18, 0x3d, 0xb6, 0x8c,
	0xa6, 0x58, 0x84, 0x36, 0x7b, 0x22, 0x7a, 0x49, 0x9a, 0xd0, 0x7d, 0x70, 0xa8, 0x83, 0xc3, 0x23,
	0xcb, 0x61, 0xa2, 0x2b, 0x50, 0x9e, 0x97, 0x53, 0x97, 0x10, 0x98, 0x5c, 0xf1, 0x4d, 0xac, 0x7a,
	0x47, 0x9e, 0x33, 0x38, 0xf4, 0x0b, 0x11, 0xfa, 0x86, 0x10, 0xd3, 0x40, 0x30, 0x6f, 0x80, 0xf9,
	0x7f, 0x0e, 0x11, 0x4a, 0xd0, 0xbd, 0x20, 0xa0, 0x1e, 0x69, 0x99, 0x99, 0xf1, 0x6f, 0x82, 0x7f,
	0x31, 0x84, 0x80, 0x84, 0x09, 0x00, 0x90, 0x6a, 0x40, 0xc2, 0x44, 0x01, 0x80, 0x02, 0x04, 0x24,
	0x4c, 0x18, 0x40, 0x2b, 0x03, 0xa4, 0x21, 0xfa, 0x96, 0xb4, 0xf0, 0x92, 0x01, 0xa1, 0x0d, 0x84,
	0x9e, 0x45, 0xf0, 0x4d, 0x0d, 0x22, 0x8a, 0x12, 0x7a, 0x4e, 0xda, 0x38, 0x35, 0x90, 0xfb, 0x00,
	0xd9, 0x8b, 0xe9, 0x6d, 0x18, 0x27, 0x80, 0x1c, 0x57, 0x6c, 0x63, 0x06, 0x63, 0xba, 0x8d, 0x5c,
	0xa0, 0xb7, 0x61, 0x66, 0x86, 0xd0, 0x31, 0xdb, 0x28, 0x84, 0xf4, 0xa5, 0xcb, 0xaf, 0x3b, 0x40,
	0x1e, 0x54, 0x5c, 0xba, 0x59, 0x56, 0x96, 0x5e, 0xba, 0x7d, 0x21, 0x1d, 0x90, 0x4e, 0x1e, 0x31,
	0xc0, 0x13, 0x00, 0x96, 0xc3, 0x1a, 0x9a, 0x7f, 0xfe, 0x00, 0xa5, 0x00, 0x7d, 0x6e, 0x37, 0x28,
	0x2b, 0xf3, 0xd9, 0x9c, 0x8b, 0xd0, 0x2f, 0x09, 0xe9, 0x6b, 0xd2, 0xd0, 0xcf, 0x17, 0x98, 0x3c,
	0xac, 0x58, 0xf9, 0x44, 0x44, 0x21, 0xca, 0xb3, 0x62, 0xdd, 0x3f, 0x7c, 0x38, 0x41, 0x7b, 0x0a,
	0x5a, 0xd7, 0xfe, 0xd4, 0x4c, 0x0d, 0xca, 0x8b, 0x92, 0xf1, 0xcb, 0x9b, 0xad, 0xeb, 0xdc, 0x6e,
	0x5d, 0xe7, 0xcf, 0xd6, 0x75, 0xbe, 0xed, 0xdc, 0xda, 0xed, 0xce, 0xad, 0xfd, 0xda, 0xb9, 0xb5,
	0x8f, 0xdd, 0xf4, 0x25, 0xf9, 0x9a, 0xbd, 0x29, 0x2a, 0x59, 0x33, 0x79, 0x5d, 0x87, 0xf7, 0xe4,
	0xd5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0xae, 0x3a, 0xb3, 0x3b, 0x06, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AddressList) > 0 {
		for iNdEx := len(m.AddressList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AddressList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xa2
		}
	}
	if len(m.GridList) > 0 {
		for iNdEx := len(m.GridList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GridList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x9a
		}
	}
	if len(m.PermissionList) > 0 {
		for iNdEx := len(m.PermissionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PermissionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x92
		}
	}
	if m.SubstationCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SubstationCount))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.SubstationList) > 0 {
		for iNdEx := len(m.SubstationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SubstationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if m.StructCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.StructCount))
		i--
		dAtA[i] = 0x78
	}
	if len(m.StructList) > 0 {
		for iNdEx := len(m.StructList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StructList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if m.ReactorCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ReactorCount))
		i--
		dAtA[i] = 0x68
	}
	if len(m.ReactorList) > 0 {
		for iNdEx := len(m.ReactorList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReactorList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.PlayerCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PlayerCount))
		i--
		dAtA[i] = 0x58
	}
	if len(m.PlayerList) > 0 {
		for iNdEx := len(m.PlayerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PlayerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.PlanetCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PlanetCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.PlanetList) > 0 {
		for iNdEx := len(m.PlanetList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PlanetList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.GuildCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.GuildCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.GuildList) > 0 {
		for iNdEx := len(m.GuildList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GuildList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.InfusionList) > 0 {
		for iNdEx := len(m.InfusionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InfusionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AllocationList) > 0 {
		for iNdEx := len(m.AllocationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllocationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.AllocationList) > 0 {
		for _, e := range m.AllocationList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.InfusionList) > 0 {
		for _, e := range m.InfusionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GuildList) > 0 {
		for _, e := range m.GuildList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.GuildCount != 0 {
		n += 1 + sovGenesis(uint64(m.GuildCount))
	}
	if len(m.PlanetList) > 0 {
		for _, e := range m.PlanetList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PlanetCount != 0 {
		n += 1 + sovGenesis(uint64(m.PlanetCount))
	}
	if len(m.PlayerList) > 0 {
		for _, e := range m.PlayerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PlayerCount != 0 {
		n += 1 + sovGenesis(uint64(m.PlayerCount))
	}
	if len(m.ReactorList) > 0 {
		for _, e := range m.ReactorList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ReactorCount != 0 {
		n += 1 + sovGenesis(uint64(m.ReactorCount))
	}
	if len(m.StructList) > 0 {
		for _, e := range m.StructList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.StructCount != 0 {
		n += 1 + sovGenesis(uint64(m.StructCount))
	}
	if len(m.SubstationList) > 0 {
		for _, e := range m.SubstationList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if m.SubstationCount != 0 {
		n += 2 + sovGenesis(uint64(m.SubstationCount))
	}
	if len(m.PermissionList) > 0 {
		for _, e := range m.PermissionList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GridList) > 0 {
		for _, e := range m.GridList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AddressList) > 0 {
		for _, e := range m.AddressList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllocationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllocationList = append(m.AllocationList, Allocation{})
			if err := m.AllocationList[len(m.AllocationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InfusionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InfusionList = append(m.InfusionList, Infusion{})
			if err := m.InfusionList[len(m.InfusionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuildList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuildList = append(m.GuildList, Guild{})
			if err := m.GuildList[len(m.GuildList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuildCount", wireType)
			}
			m.GuildCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GuildCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanetList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlanetList = append(m.PlanetList, Planet{})
			if err := m.PlanetList[len(m.PlanetList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanetCount", wireType)
			}
			m.PlanetCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlanetCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlayerList = append(m.PlayerList, Player{})
			if err := m.PlayerList[len(m.PlayerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerCount", wireType)
			}
			m.PlayerCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReactorList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReactorList = append(m.ReactorList, Reactor{})
			if err := m.ReactorList[len(m.ReactorList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReactorCount", wireType)
			}
			m.ReactorCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReactorCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StructList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StructList = append(m.StructList, Struct{})
			if err := m.StructList[len(m.StructList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StructCount", wireType)
			}
			m.StructCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StructCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubstationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubstationList = append(m.SubstationList, Substation{})
			if err := m.SubstationList[len(m.SubstationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubstationCount", wireType)
			}
			m.SubstationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubstationCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PermissionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PermissionList = append(m.PermissionList, &PermissionRecord{})
			if err := m.PermissionList[len(m.PermissionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GridList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GridList = append(m.GridList, &GridRecord{})
			if err := m.GridList[len(m.GridList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressList = append(m.AddressList, &AddressRecord{})
			if err := m.AddressList[len(m.AddressList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
