// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: structs/structs/keys.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ObjectType int32

const (
	ObjectType_guild      ObjectType = 0
	ObjectType_player     ObjectType = 1
	ObjectType_planet     ObjectType = 2
	ObjectType_reactor    ObjectType = 3
	ObjectType_substation ObjectType = 4
	ObjectType_struct     ObjectType = 5
	ObjectType_allocation ObjectType = 6
	ObjectType_infusion   ObjectType = 7
	ObjectType_address    ObjectType = 8
	ObjectType_fleet      ObjectType = 9
)

var ObjectType_name = map[int32]string{
	0: "guild",
	1: "player",
	2: "planet",
	3: "reactor",
	4: "substation",
	5: "struct",
	6: "allocation",
	7: "infusion",
	8: "address",
	9: "fleet",
}

var ObjectType_value = map[string]int32{
	"guild":      0,
	"player":     1,
	"planet":     2,
	"reactor":    3,
	"substation": 4,
	"struct":     5,
	"allocation": 6,
	"infusion":   7,
	"address":    8,
	"fleet":      9,
}

func (x ObjectType) String() string {
	return proto.EnumName(ObjectType_name, int32(x))
}

func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{0}
}

type GridAttributeType int32

const (
	GridAttributeType_ore                    GridAttributeType = 0
	GridAttributeType_fuel                   GridAttributeType = 1
	GridAttributeType_capacity               GridAttributeType = 2
	GridAttributeType_load                   GridAttributeType = 3
	GridAttributeType_structsLoad            GridAttributeType = 4
	GridAttributeType_power                  GridAttributeType = 5
	GridAttributeType_connectionCapacity     GridAttributeType = 6
	GridAttributeType_connectionCount        GridAttributeType = 7
	GridAttributeType_allocationPointerStart GridAttributeType = 8
	GridAttributeType_allocationPointerEnd   GridAttributeType = 9
	GridAttributeType_proxyNonce             GridAttributeType = 10
	GridAttributeType_lastAction             GridAttributeType = 11
	GridAttributeType_nonce                  GridAttributeType = 12
	GridAttributeType_ready                  GridAttributeType = 13
)

var GridAttributeType_name = map[int32]string{
	0:  "ore",
	1:  "fuel",
	2:  "capacity",
	3:  "load",
	4:  "structsLoad",
	5:  "power",
	6:  "connectionCapacity",
	7:  "connectionCount",
	8:  "allocationPointerStart",
	9:  "allocationPointerEnd",
	10: "proxyNonce",
	11: "lastAction",
	12: "nonce",
	13: "ready",
}

var GridAttributeType_value = map[string]int32{
	"ore":                    0,
	"fuel":                   1,
	"capacity":               2,
	"load":                   3,
	"structsLoad":            4,
	"power":                  5,
	"connectionCapacity":     6,
	"connectionCount":        7,
	"allocationPointerStart": 8,
	"allocationPointerEnd":   9,
	"proxyNonce":             10,
	"lastAction":             11,
	"nonce":                  12,
	"ready":                  13,
}

func (x GridAttributeType) String() string {
	return proto.EnumName(GridAttributeType_name, int32(x))
}

func (GridAttributeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{1}
}

type AllocationType int32

const (
	AllocationType_static    AllocationType = 0
	AllocationType_dynamic   AllocationType = 1
	AllocationType_automated AllocationType = 2
)

var AllocationType_name = map[int32]string{
	0: "static",
	1: "dynamic",
	2: "automated",
}

var AllocationType_value = map[string]int32{
	"static":    0,
	"dynamic":   1,
	"automated": 2,
}

func (x AllocationType) String() string {
	return proto.EnumName(AllocationType_name, int32(x))
}

func (AllocationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{2}
}

type GuildJoinBypassLevel int32

const (
	GuildJoinBypassLevel_closed       GuildJoinBypassLevel = 0
	GuildJoinBypassLevel_permissioned GuildJoinBypassLevel = 1
	GuildJoinBypassLevel_member       GuildJoinBypassLevel = 2
)

var GuildJoinBypassLevel_name = map[int32]string{
	0: "closed",
	1: "permissioned",
	2: "member",
}

var GuildJoinBypassLevel_value = map[string]int32{
	"closed":       0,
	"permissioned": 1,
	"member":       2,
}

func (x GuildJoinBypassLevel) String() string {
	return proto.EnumName(GuildJoinBypassLevel_name, int32(x))
}

func (GuildJoinBypassLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{3}
}

type GuildJoinType int32

const (
	GuildJoinType_invite  GuildJoinType = 0
	GuildJoinType_request GuildJoinType = 1
	GuildJoinType_direct  GuildJoinType = 2
	GuildJoinType_proxy   GuildJoinType = 3
)

var GuildJoinType_name = map[int32]string{
	0: "invite",
	1: "request",
	2: "direct",
	3: "proxy",
}

var GuildJoinType_value = map[string]int32{
	"invite":  0,
	"request": 1,
	"direct":  2,
	"proxy":   3,
}

func (x GuildJoinType) String() string {
	return proto.EnumName(GuildJoinType_name, int32(x))
}

func (GuildJoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{4}
}

type RegistrationStatus int32

const (
	RegistrationStatus_proposed RegistrationStatus = 0
	RegistrationStatus_approved RegistrationStatus = 1
	RegistrationStatus_denied   RegistrationStatus = 2
	RegistrationStatus_revoked  RegistrationStatus = 3
)

var RegistrationStatus_name = map[int32]string{
	0: "proposed",
	1: "approved",
	2: "denied",
	3: "revoked",
}

var RegistrationStatus_value = map[string]int32{
	"proposed": 0,
	"approved": 1,
	"denied":   2,
	"revoked":  3,
}

func (x RegistrationStatus) String() string {
	return proto.EnumName(RegistrationStatus_name, int32(x))
}

func (RegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{5}
}

type Ambit int32

const (
	Ambit_none  Ambit = 0
	Ambit_water Ambit = 1
	Ambit_land  Ambit = 2
	Ambit_air   Ambit = 3
	Ambit_space Ambit = 4
	Ambit_local Ambit = 5
)

var Ambit_name = map[int32]string{
	0: "none",
	1: "water",
	2: "land",
	3: "air",
	4: "space",
	5: "local",
}

var Ambit_value = map[string]int32{
	"none":  0,
	"water": 1,
	"land":  2,
	"air":   3,
	"space": 4,
	"local": 5,
}

func (x Ambit) String() string {
	return proto.EnumName(Ambit_name, int32(x))
}

func (Ambit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{6}
}

type PlanetStatus int32

const (
	PlanetStatus_active   PlanetStatus = 0
	PlanetStatus_complete PlanetStatus = 1
)

var PlanetStatus_name = map[int32]string{
	0: "active",
	1: "complete",
}

var PlanetStatus_value = map[string]int32{
	"active":   0,
	"complete": 1,
}

func (x PlanetStatus) String() string {
	return proto.EnumName(PlanetStatus_name, int32(x))
}

func (PlanetStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{7}
}

type StructAttributeType int32

const (
	StructAttributeType_health               StructAttributeType = 0
	StructAttributeType_status               StructAttributeType = 1
	StructAttributeType_blockStartBuild      StructAttributeType = 2
	StructAttributeType_blockStartOreMine    StructAttributeType = 3
	StructAttributeType_blockStartOreRefine  StructAttributeType = 4
	StructAttributeType_protectedStructIndex StructAttributeType = 5
	StructAttributeType_typeCount            StructAttributeType = 6
)

var StructAttributeType_name = map[int32]string{
	0: "health",
	1: "status",
	2: "blockStartBuild",
	3: "blockStartOreMine",
	4: "blockStartOreRefine",
	5: "protectedStructIndex",
	6: "typeCount",
}

var StructAttributeType_value = map[string]int32{
	"health":               0,
	"status":               1,
	"blockStartBuild":      2,
	"blockStartOreMine":    3,
	"blockStartOreRefine":  4,
	"protectedStructIndex": 5,
	"typeCount":            6,
}

func (x StructAttributeType) String() string {
	return proto.EnumName(StructAttributeType_name, int32(x))
}

func (StructAttributeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{8}
}

type PlanetAttributeType int32

const (
	PlanetAttributeType_planetaryShield                                      PlanetAttributeType = 0
	PlanetAttributeType_repairNetworkQuantity                                PlanetAttributeType = 1
	PlanetAttributeType_defensiveCannonQuantity                              PlanetAttributeType = 2
	PlanetAttributeType_coordinatedGlobalShieldNetworkQuantity               PlanetAttributeType = 3
	PlanetAttributeType_lowOrbitBallisticsInterceptorNetworkQuantity         PlanetAttributeType = 4
	PlanetAttributeType_advancedLowOrbitBallisticsInterceptorNetworkQuantity PlanetAttributeType = 5
	PlanetAttributeType_orbitalJammingStationQuantity                        PlanetAttributeType = 6
	PlanetAttributeType_advancedOrbitalJammingStationQuantity                PlanetAttributeType = 7
)

var PlanetAttributeType_name = map[int32]string{
	0: "planetaryShield",
	1: "repairNetworkQuantity",
	2: "defensiveCannonQuantity",
	3: "coordinatedGlobalShieldNetworkQuantity",
	4: "lowOrbitBallisticsInterceptorNetworkQuantity",
	5: "advancedLowOrbitBallisticsInterceptorNetworkQuantity",
	6: "orbitalJammingStationQuantity",
	7: "advancedOrbitalJammingStationQuantity",
}

var PlanetAttributeType_value = map[string]int32{
	"planetaryShield":                                      0,
	"repairNetworkQuantity":                                1,
	"defensiveCannonQuantity":                              2,
	"coordinatedGlobalShieldNetworkQuantity":               3,
	"lowOrbitBallisticsInterceptorNetworkQuantity":         4,
	"advancedLowOrbitBallisticsInterceptorNetworkQuantity": 5,
	"orbitalJammingStationQuantity":                        6,
	"advancedOrbitalJammingStationQuantity":                7,
}

func (x PlanetAttributeType) String() string {
	return proto.EnumName(PlanetAttributeType_name, int32(x))
}

func (PlanetAttributeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{9}
}

type TechWeaponSystem int32

const (
	TechWeaponSystem_primaryWeapon   TechWeaponSystem = 0
	TechWeaponSystem_secondaryWeapon TechWeaponSystem = 1
)

var TechWeaponSystem_name = map[int32]string{
	0: "primaryWeapon",
	1: "secondaryWeapon",
}

var TechWeaponSystem_value = map[string]int32{
	"primaryWeapon":   0,
	"secondaryWeapon": 1,
}

func (x TechWeaponSystem) String() string {
	return proto.EnumName(TechWeaponSystem_name, int32(x))
}

func (TechWeaponSystem) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{10}
}

type TechWeaponControl int32

const (
	TechWeaponControl_noWeaponControl TechWeaponControl = 0
	TechWeaponControl_guided          TechWeaponControl = 1
	TechWeaponControl_unguided        TechWeaponControl = 2
)

var TechWeaponControl_name = map[int32]string{
	0: "noWeaponControl",
	1: "guided",
	2: "unguided",
}

var TechWeaponControl_value = map[string]int32{
	"noWeaponControl": 0,
	"guided":          1,
	"unguided":        2,
}

func (x TechWeaponControl) String() string {
	return proto.EnumName(TechWeaponControl_name, int32(x))
}

func (TechWeaponControl) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{11}
}

type TechActiveWeaponry int32

const (
	TechActiveWeaponry_noActiveWeaponry TechActiveWeaponry = 0
	TechActiveWeaponry_guidedWeaponry   TechActiveWeaponry = 1
	TechActiveWeaponry_unguidedWeaponry TechActiveWeaponry = 2
	TechActiveWeaponry_attackRun        TechActiveWeaponry = 3
	TechActiveWeaponry_selfDestruct     TechActiveWeaponry = 4
)

var TechActiveWeaponry_name = map[int32]string{
	0: "noActiveWeaponry",
	1: "guidedWeaponry",
	2: "unguidedWeaponry",
	3: "attackRun",
	4: "selfDestruct",
}

var TechActiveWeaponry_value = map[string]int32{
	"noActiveWeaponry": 0,
	"guidedWeaponry":   1,
	"unguidedWeaponry": 2,
	"attackRun":        3,
	"selfDestruct":     4,
}

func (x TechActiveWeaponry) String() string {
	return proto.EnumName(TechActiveWeaponry_name, int32(x))
}

func (TechActiveWeaponry) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{12}
}

type TechPassiveWeaponry int32

const (
	TechPassiveWeaponry_noPassiveWeaponry     TechPassiveWeaponry = 0
	TechPassiveWeaponry_counterAttack         TechPassiveWeaponry = 1
	TechPassiveWeaponry_strongCounterAttack   TechPassiveWeaponry = 2
	TechPassiveWeaponry_advancedCounterAttack TechPassiveWeaponry = 3
	TechPassiveWeaponry_lastResort            TechPassiveWeaponry = 4
)

var TechPassiveWeaponry_name = map[int32]string{
	0: "noPassiveWeaponry",
	1: "counterAttack",
	2: "strongCounterAttack",
	3: "advancedCounterAttack",
	4: "lastResort",
}

var TechPassiveWeaponry_value = map[string]int32{
	"noPassiveWeaponry":     0,
	"counterAttack":         1,
	"strongCounterAttack":   2,
	"advancedCounterAttack": 3,
	"lastResort":            4,
}

func (x TechPassiveWeaponry) String() string {
	return proto.EnumName(TechPassiveWeaponry_name, int32(x))
}

func (TechPassiveWeaponry) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{13}
}

type TechUnitDefenses int32

const (
	TechUnitDefenses_noUnitDefenses       TechUnitDefenses = 0
	TechUnitDefenses_defensiveManeuver    TechUnitDefenses = 1
	TechUnitDefenses_signalJamming        TechUnitDefenses = 2
	TechUnitDefenses_armour               TechUnitDefenses = 3
	TechUnitDefenses_indirectCombatModule TechUnitDefenses = 4
	TechUnitDefenses_stealthMode          TechUnitDefenses = 5
	TechUnitDefenses_perimeterFencing     TechUnitDefenses = 6
	TechUnitDefenses_reinforcedWalls      TechUnitDefenses = 7
)

var TechUnitDefenses_name = map[int32]string{
	0: "noUnitDefenses",
	1: "defensiveManeuver",
	2: "signalJamming",
	3: "armour",
	4: "indirectCombatModule",
	5: "stealthMode",
	6: "perimeterFencing",
	7: "reinforcedWalls",
}

var TechUnitDefenses_value = map[string]int32{
	"noUnitDefenses":       0,
	"defensiveManeuver":    1,
	"signalJamming":        2,
	"armour":               3,
	"indirectCombatModule": 4,
	"stealthMode":          5,
	"perimeterFencing":     6,
	"reinforcedWalls":      7,
}

func (x TechUnitDefenses) String() string {
	return proto.EnumName(TechUnitDefenses_name, int32(x))
}

func (TechUnitDefenses) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{14}
}

type TechOreReserveDefenses int32

const (
	TechOreReserveDefenses_noOreReserveDefenses              TechOreReserveDefenses = 0
	TechOreReserveDefenses_coordinatedReserveResponseTracker TechOreReserveDefenses = 1
	TechOreReserveDefenses_rapidResponsePackage              TechOreReserveDefenses = 2
	TechOreReserveDefenses_activeScanning                    TechOreReserveDefenses = 3
	TechOreReserveDefenses_monitoringStation                 TechOreReserveDefenses = 4
	TechOreReserveDefenses_oreBunker                         TechOreReserveDefenses = 5
)

var TechOreReserveDefenses_name = map[int32]string{
	0: "noOreReserveDefenses",
	1: "coordinatedReserveResponseTracker",
	2: "rapidResponsePackage",
	3: "activeScanning",
	4: "monitoringStation",
	5: "oreBunker",
}

var TechOreReserveDefenses_value = map[string]int32{
	"noOreReserveDefenses":              0,
	"coordinatedReserveResponseTracker": 1,
	"rapidResponsePackage":              2,
	"activeScanning":                    3,
	"monitoringStation":                 4,
	"oreBunker":                         5,
}

func (x TechOreReserveDefenses) String() string {
	return proto.EnumName(TechOreReserveDefenses_name, int32(x))
}

func (TechOreReserveDefenses) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{15}
}

type TechPlanetaryDefenses int32

const (
	TechPlanetaryDefenses_noPlanetaryDefense                  TechPlanetaryDefenses = 0
	TechPlanetaryDefenses_defensiveCannon                     TechPlanetaryDefenses = 1
	TechPlanetaryDefenses_lowOrbitBallisticInterceptorNetwork TechPlanetaryDefenses = 2
)

var TechPlanetaryDefenses_name = map[int32]string{
	0: "noPlanetaryDefense",
	1: "defensiveCannon",
	2: "lowOrbitBallisticInterceptorNetwork",
}

var TechPlanetaryDefenses_value = map[string]int32{
	"noPlanetaryDefense":                  0,
	"defensiveCannon":                     1,
	"lowOrbitBallisticInterceptorNetwork": 2,
}

func (x TechPlanetaryDefenses) String() string {
	return proto.EnumName(TechPlanetaryDefenses_name, int32(x))
}

func (TechPlanetaryDefenses) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{16}
}

type TechStorageFacilities int32

const (
	TechStorageFacilities_noStorageFacilities TechStorageFacilities = 0
	TechStorageFacilities_dock                TechStorageFacilities = 1
	TechStorageFacilities_hanger              TechStorageFacilities = 2
	TechStorageFacilities_fleetBase           TechStorageFacilities = 3
)

var TechStorageFacilities_name = map[int32]string{
	0: "noStorageFacilities",
	1: "dock",
	2: "hanger",
	3: "fleetBase",
}

var TechStorageFacilities_value = map[string]int32{
	"noStorageFacilities": 0,
	"dock":                1,
	"hanger":              2,
	"fleetBase":           3,
}

func (x TechStorageFacilities) String() string {
	return proto.EnumName(TechStorageFacilities_name, int32(x))
}

func (TechStorageFacilities) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{17}
}

type TechPlanetaryMining int32

const (
	TechPlanetaryMining_noPlanetaryMining TechPlanetaryMining = 0
	TechPlanetaryMining_oreMiningRig      TechPlanetaryMining = 1
)

var TechPlanetaryMining_name = map[int32]string{
	0: "noPlanetaryMining",
	1: "oreMiningRig",
}

var TechPlanetaryMining_value = map[string]int32{
	"noPlanetaryMining": 0,
	"oreMiningRig":      1,
}

func (x TechPlanetaryMining) String() string {
	return proto.EnumName(TechPlanetaryMining_name, int32(x))
}

func (TechPlanetaryMining) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{18}
}

type TechPlanetaryRefineries int32

const (
	TechPlanetaryRefineries_noPlanetaryRefinery TechPlanetaryRefineries = 0
	TechPlanetaryRefineries_oreRefinery         TechPlanetaryRefineries = 1
)

var TechPlanetaryRefineries_name = map[int32]string{
	0: "noPlanetaryRefinery",
	1: "oreRefinery",
}

var TechPlanetaryRefineries_value = map[string]int32{
	"noPlanetaryRefinery": 0,
	"oreRefinery":         1,
}

func (x TechPlanetaryRefineries) String() string {
	return proto.EnumName(TechPlanetaryRefineries_name, int32(x))
}

func (TechPlanetaryRefineries) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{19}
}

type TechPowerGeneration int32

const (
	TechPowerGeneration_noPowerGeneration TechPowerGeneration = 0
	TechPowerGeneration_smallGenerator    TechPowerGeneration = 1
	TechPowerGeneration_mediumGenerator   TechPowerGeneration = 2
	TechPowerGeneration_largeGenerator    TechPowerGeneration = 3
)

var TechPowerGeneration_name = map[int32]string{
	0: "noPowerGeneration",
	1: "smallGenerator",
	2: "mediumGenerator",
	3: "largeGenerator",
}

var TechPowerGeneration_value = map[string]int32{
	"noPowerGeneration": 0,
	"smallGenerator":    1,
	"mediumGenerator":   2,
	"largeGenerator":    3,
}

func (x TechPowerGeneration) String() string {
	return proto.EnumName(TechPowerGeneration_name, int32(x))
}

func (TechPowerGeneration) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2b5c851dc116405, []int{20}
}

func init() {
	proto.RegisterEnum("structs.structs.ObjectType", ObjectType_name, ObjectType_value)
	proto.RegisterEnum("structs.structs.GridAttributeType", GridAttributeType_name, GridAttributeType_value)
	proto.RegisterEnum("structs.structs.AllocationType", AllocationType_name, AllocationType_value)
	proto.RegisterEnum("structs.structs.GuildJoinBypassLevel", GuildJoinBypassLevel_name, GuildJoinBypassLevel_value)
	proto.RegisterEnum("structs.structs.GuildJoinType", GuildJoinType_name, GuildJoinType_value)
	proto.RegisterEnum("structs.structs.RegistrationStatus", RegistrationStatus_name, RegistrationStatus_value)
	proto.RegisterEnum("structs.structs.Ambit", Ambit_name, Ambit_value)
	proto.RegisterEnum("structs.structs.PlanetStatus", PlanetStatus_name, PlanetStatus_value)
	proto.RegisterEnum("structs.structs.StructAttributeType", StructAttributeType_name, StructAttributeType_value)
	proto.RegisterEnum("structs.structs.PlanetAttributeType", PlanetAttributeType_name, PlanetAttributeType_value)
	proto.RegisterEnum("structs.structs.TechWeaponSystem", TechWeaponSystem_name, TechWeaponSystem_value)
	proto.RegisterEnum("structs.structs.TechWeaponControl", TechWeaponControl_name, TechWeaponControl_value)
	proto.RegisterEnum("structs.structs.TechActiveWeaponry", TechActiveWeaponry_name, TechActiveWeaponry_value)
	proto.RegisterEnum("structs.structs.TechPassiveWeaponry", TechPassiveWeaponry_name, TechPassiveWeaponry_value)
	proto.RegisterEnum("structs.structs.TechUnitDefenses", TechUnitDefenses_name, TechUnitDefenses_value)
	proto.RegisterEnum("structs.structs.TechOreReserveDefenses", TechOreReserveDefenses_name, TechOreReserveDefenses_value)
	proto.RegisterEnum("structs.structs.TechPlanetaryDefenses", TechPlanetaryDefenses_name, TechPlanetaryDefenses_value)
	proto.RegisterEnum("structs.structs.TechStorageFacilities", TechStorageFacilities_name, TechStorageFacilities_value)
	proto.RegisterEnum("structs.structs.TechPlanetaryMining", TechPlanetaryMining_name, TechPlanetaryMining_value)
	proto.RegisterEnum("structs.structs.TechPlanetaryRefineries", TechPlanetaryRefineries_name, TechPlanetaryRefineries_value)
	proto.RegisterEnum("structs.structs.TechPowerGeneration", TechPowerGeneration_name, TechPowerGeneration_value)
}

func init() { proto.RegisterFile("structs/structs/keys.proto", fileDescriptor_d2b5c851dc116405) }

var fileDescriptor_d2b5c851dc116405 = []byte{
	// 1331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0x1c, 0xb9,
	0x11, 0x9e, 0x9e, 0xd1, 0x8c, 0xa4, 0x92, 0x64, 0x51, 0xd4, 0x6f, 0x1c, 0x44, 0x80, 0x11, 0x38,
	0x3f, 0x8d, 0xc0, 0x4e, 0x90, 0x1c, 0x8c, 0x1c, 0x92, 0x48, 0xf2, 0x0f, 0x6c, 0x58, 0xb6, 0xa3,
	0xb1, 0x61, 0x20, 0x37, 0x0e, 0xbb, 0x34, 0x62, 0xd4, 0xcd, 0xea, 0x90, 0xec, 0x91, 0xe7, 0x9c,
	0xfb, 0x62, 0xef, 0xfb, 0x0c, 0x7b, 0xd9, 0xa7, 0xf0, 0xd1, 0xc7, 0x3d, 0x2e, 0xec, 0x47, 0xd8,
	0x17, 0x58, 0x14, 0x39, 0x3f, 0x1a, 0x09, 0x58, 0x60, 0x4f, 0xdd, 0xfd, 0x15, 0x59, 0xf5, 0xb1,
	0xea, 0xab, 0x62, 0xc3, 0x5d, 0x1f, 0x5c, 0xa3, 0x83, 0x7f, 0x38, 0x7d, 0x5e, 0xe2, 0xd8, 0x3f,
	0xa8, 0x1d, 0x05, 0x92, 0x9b, 0x13, 0xec, 0xc1, 0xe4, 0x79, 0x77, 0x67, 0x48, 0x43, 0x8a, 0xb6,
	0x87, 0xfc, 0x96, 0x96, 0xe5, 0x5f, 0x65, 0x00, 0x34, 0xf8, 0x2f, 0xea, 0xf0, 0x76, 0x5c, 0xa3,
	0x5c, 0x85, 0xee, 0xb0, 0x31, 0x65, 0x21, 0x5a, 0x12, 0xa0, 0x57, 0x97, 0x6a, 0x8c, 0x4e, 0x64,
	0x93, 0x77, 0x8b, 0x41, 0xb4, 0xe5, 0x1a, 0x2c, 0x3b, 0x54, 0x3a, 0x90, 0x13, 0x1d, 0x79, 0x07,
	0xc0, 0x37, 0x03, 0x1f, 0x54, 0x30, 0x64, 0xc5, 0x12, 0x2f, 0x4c, 0xf1, 0x44, 0x97, 0x6d, 0xaa,
	0x2c, 0x49, 0x27, 0x5b, 0x4f, 0xae, 0xc3, 0x8a, 0xb1, 0xe7, 0x8d, 0xe7, 0xaf, 0x65, 0x76, 0xa3,
	0x8a, 0xc2, 0xa1, 0xf7, 0x62, 0x85, 0xc3, 0x9e, 0x97, 0x88, 0x41, 0xac, 0xe6, 0x3f, 0x66, 0xb0,
	0x35, 0x74, 0xa6, 0x38, 0x0a, 0xc1, 0x99, 0x41, 0x13, 0x30, 0xf2, 0x5a, 0x86, 0x0e, 0x39, 0x14,
	0x2d, 0xb9, 0x02, 0x4b, 0xe7, 0x0d, 0x96, 0x22, 0x63, 0x77, 0x5a, 0xd5, 0x4a, 0x9b, 0x30, 0x16,
	0x6d, 0xc6, 0x4b, 0x52, 0x85, 0xe8, 0xc8, 0x4d, 0x58, 0x9b, 0x1c, 0xf9, 0x25, 0x03, 0x4b, 0xec,
	0xbc, 0xa6, 0x2b, 0x74, 0xa2, 0x2b, 0xf7, 0x40, 0x6a, 0xb2, 0x16, 0x35, 0x53, 0x3a, 0x99, 0xee,
	0xee, 0xc9, 0x6d, 0xd8, 0xbc, 0x86, 0x53, 0x63, 0x83, 0x58, 0x96, 0x77, 0x61, 0x6f, 0xce, 0xff,
	0x0d, 0x19, 0x1b, 0xd0, 0xf5, 0x83, 0x72, 0x41, 0xac, 0xc8, 0x03, 0xd8, 0xb9, 0x65, 0x7b, 0x62,
	0x0b, 0xb1, 0xca, 0xa7, 0xae, 0x1d, 0x7d, 0x18, 0xbf, 0x22, 0xab, 0x51, 0x00, 0x7f, 0x97, 0xca,
	0x87, 0xa3, 0xe8, 0x5a, 0xac, 0x31, 0x1b, 0x1b, 0x4d, 0xeb, 0xfc, 0xea, 0x50, 0x15, 0x63, 0xb1,
	0x91, 0x3f, 0x82, 0x3b, 0x73, 0x7f, 0xf1, 0xc4, 0x31, 0x93, 0x2a, 0x18, 0x2d, 0x5a, 0x9c, 0xab,
	0x62, 0x6c, 0x55, 0x65, 0xb4, 0xc8, 0xe4, 0x06, 0xac, 0xaa, 0x26, 0x50, 0xa5, 0x02, 0x16, 0xa2,
	0x9d, 0xff, 0x0b, 0x76, 0x62, 0xc5, 0x5e, 0x90, 0xb1, 0xc7, 0xe3, 0x5a, 0x79, 0xff, 0x12, 0x47,
	0x58, 0xf2, 0x7e, 0x5d, 0x92, 0x47, 0x2e, 0xa5, 0x80, 0xf5, 0x1a, 0x5d, 0x65, 0x3c, 0xe7, 0x1e,
	0x8b, 0x54, 0xd0, 0x0a, 0xab, 0x01, 0x3a, 0xd1, 0xce, 0xff, 0x09, 0x1b, 0x33, 0x0f, 0xd3, 0xd0,
	0xc6, 0x8e, 0x4c, 0xc0, 0x14, 0xda, 0xe1, 0xff, 0x1a, 0xf4, 0x21, 0xed, 0x2a, 0x8c, 0x43, 0xcd,
	0x32, 0xe0, 0xac, 0xf2, 0x39, 0x45, 0x27, 0x7f, 0x0e, 0xd2, 0xe1, 0xd0, 0xf8, 0xe0, 0x22, 0xfd,
	0x7e, 0x50, 0xa1, 0xf1, 0x5c, 0x9f, 0xda, 0x51, 0x3d, 0xa1, 0xb0, 0x0e, 0x2b, 0xaa, 0xae, 0x1d,
	0x8d, 0xa6, 0xe1, 0x0b, 0xb4, 0x86, 0x0f, 0x90, 0x22, 0x8c, 0xe8, 0x12, 0x0b, 0xd1, 0xc9, 0x9f,
	0x40, 0x57, 0x55, 0x03, 0x13, 0xb8, 0x9e, 0x96, 0x2c, 0x33, 0x58, 0x85, 0xee, 0x95, 0x0a, 0x51,
	0x86, 0x5c, 0x64, 0x65, 0x79, 0xd3, 0x32, 0x74, 0x94, 0x61, 0x01, 0xae, 0x42, 0xd7, 0xd7, 0x4a,
	0x63, 0xaa, 0x33, 0x67, 0xb0, 0x14, 0xdd, 0xfc, 0x0f, 0xb0, 0x9e, 0xf4, 0x3a, 0xe1, 0x02, 0xd0,
	0x53, 0x3a, 0x98, 0x11, 0x26, 0x26, 0x9a, 0xaa, 0xba, 0xc4, 0x80, 0x22, 0xcb, 0xbf, 0xc9, 0x60,
	0x3b, 0xc9, 0x65, 0x51, 0x70, 0x00, 0xbd, 0x0b, 0x54, 0x65, 0xb8, 0x48, 0x9d, 0xe0, 0xa3, 0x1f,
	0x91, 0xb1, 0x52, 0x06, 0x25, 0xe9, 0xcb, 0x28, 0x84, 0xe3, 0xd8, 0x2a, 0x6d, 0xb9, 0x0b, 0x5b,
	0x73, 0xf0, 0xb5, 0xc3, 0x53, 0x63, 0x51, 0x74, 0xe4, 0x3e, 0x6c, 0x2f, 0xc0, 0x67, 0x78, 0xce,
	0x86, 0x25, 0x56, 0x0f, 0x77, 0x1f, 0xea, 0x80, 0x45, 0x3f, 0x06, 0x7f, 0x6e, 0x0b, 0xfc, 0x20,
	0xba, 0x5c, 0xdc, 0x30, 0xae, 0x31, 0x49, 0xb0, 0x97, 0x7f, 0x6c, 0xc3, 0x76, 0x3a, 0xc8, 0x22,
	0xbb, 0x6d, 0xd8, 0x4c, 0xb0, 0x72, 0xe3, 0xfe, 0x85, 0xc1, 0xd8, 0xb0, 0xbf, 0x82, 0x5d, 0x87,
	0xb5, 0x32, 0xee, 0x15, 0x86, 0x2b, 0x72, 0x97, 0xff, 0x6e, 0x94, 0x0d, 0xac, 0xef, 0x4c, 0xfe,
	0x1a, 0xf6, 0x0b, 0x3c, 0x47, 0xeb, 0xcd, 0x08, 0x4f, 0x94, 0xb5, 0x64, 0x67, 0xc6, 0xb6, 0xcc,
	0xe1, 0x77, 0x9a, 0xc8, 0x15, 0xc6, 0xb2, 0xa4, 0x9e, 0x95, 0x34, 0x50, 0x65, 0x72, 0x7a, 0xd3,
	0x51, 0x47, 0xfe, 0x19, 0xfe, 0x54, 0xd2, 0xd5, 0x6b, 0x37, 0x30, 0xe1, 0x58, 0x95, 0xa5, 0xf1,
	0xc1, 0x68, 0xff, 0x9c, 0xd5, 0xaf, 0xb1, 0x0e, 0x74, 0x2b, 0xf4, 0x92, 0x7c, 0x04, 0x7f, 0x53,
	0xc5, 0x48, 0x59, 0x8d, 0xc5, 0xcb, 0x5f, 0xb2, 0xb3, 0x2b, 0xef, 0xc1, 0x6f, 0x88, 0x97, 0xab,
	0xf2, 0x85, 0xaa, 0x2a, 0x63, 0x87, 0xfd, 0x34, 0x66, 0x66, 0x4b, 0x7a, 0xf2, 0x8f, 0x70, 0x7f,
	0xea, 0xfc, 0xf5, 0xcf, 0x2e, 0x5d, 0xce, 0xff, 0x0e, 0x22, 0xa0, 0xbe, 0x78, 0x8f, 0xaa, 0x26,
	0xdb, 0x1f, 0xfb, 0x80, 0x95, 0xdc, 0x82, 0x8d, 0xda, 0x99, 0x4a, 0xb9, 0x71, 0x82, 0x45, 0x8b,
	0x33, 0xeb, 0x51, 0x93, 0x2d, 0xe6, 0x60, 0x96, 0x1f, 0xc3, 0xd6, 0x7c, 0xef, 0x09, 0xd9, 0xe0,
	0xa8, 0xe4, 0x95, 0x96, 0x16, 0xa0, 0x24, 0x95, 0x61, 0x63, 0x8a, 0x28, 0xf2, 0x75, 0x58, 0x69,
	0xec, 0xe4, 0xab, 0x9d, 0x37, 0x20, 0xd9, 0xc7, 0x51, 0x94, 0x61, 0xda, 0xe6, 0xc6, 0x72, 0x07,
	0x84, 0xa5, 0x45, 0x4c, 0xb4, 0xa4, 0x84, 0x3b, 0x69, 0xdf, 0x0c, 0xcb, 0x78, 0xe5, 0xd4, 0xdb,
	0x0c, 0x6d, 0xc7, 0x61, 0x10, 0x82, 0xd2, 0x97, 0x67, 0x8d, 0x15, 0x1d, 0x6e, 0x74, 0x8f, 0xe5,
	0xf9, 0x63, 0x9c, 0x0c, 0xe1, 0xa5, 0xfc, 0xff, 0x19, 0x6c, 0x73, 0xdc, 0x37, 0xca, 0xfb, 0xeb,
	0x81, 0x77, 0x61, 0xcb, 0xd2, 0x0d, 0x50, 0xb4, 0x38, 0x23, 0x9a, 0xb5, 0x87, 0xee, 0x28, 0xba,
	0x15, 0x19, 0xab, 0xd8, 0x07, 0x47, 0x76, 0x78, 0xb2, 0x60, 0x68, 0xb3, 0xde, 0xa6, 0xc9, 0x5f,
	0x34, 0x75, 0xa6, 0x43, 0xef, 0x0c, 0x3d, 0x39, 0x66, 0xf1, 0x5d, 0x96, 0xb2, 0xff, 0xce, 0x9a,
	0xf0, 0x38, 0x0a, 0x11, 0x3d, 0x9f, 0xd2, 0xd2, 0x75, 0x44, 0xb4, 0x98, 0xd6, 0x4c, 0xa8, 0xa7,
	0xca, 0x62, 0x33, 0x8a, 0x8d, 0xbf, 0x05, 0x1b, 0xde, 0x0c, 0xed, 0xac, 0xbc, 0xa2, 0x1d, 0x5b,
	0xda, 0x55, 0xd4, 0xf0, 0x10, 0x38, 0x80, 0x1d, 0x63, 0xd3, 0x64, 0x3a, 0xa1, 0x6a, 0xa0, 0xc2,
	0x29, 0x15, 0x4d, 0xc9, 0x9d, 0x16, 0x2f, 0x83, 0xd8, 0xc7, 0xa7, 0x54, 0xa0, 0xe8, 0x72, 0x1a,
	0x6b, 0x74, 0xa6, 0xc2, 0x80, 0xee, 0x29, 0x5a, 0xcd, 0xce, 0xe2, 0xfc, 0x77, 0x68, 0xec, 0x39,
	0x39, 0x8d, 0xc5, 0x7b, 0x55, 0x96, 0x5e, 0x2c, 0xe7, 0xdf, 0x66, 0xb0, 0xc7, 0xa4, 0x63, 0xe7,
	0x7a, 0x74, 0x23, 0x9c, 0x51, 0x3f, 0x80, 0x1d, 0x4b, 0xb7, 0x71, 0xd1, 0x92, 0xf7, 0xe1, 0xde,
	0xb5, 0x66, 0x9a, 0xd8, 0xcf, 0xd0, 0xd7, 0x64, 0x3d, 0xbe, 0x75, 0x4a, 0x5f, 0xc6, 0x03, 0x1d,
	0xc0, 0x8e, 0x53, 0xb5, 0x29, 0xa6, 0x96, 0x37, 0x4a, 0x5f, 0xaa, 0x21, 0x8a, 0x36, 0x67, 0x25,
	0x8d, 0xaa, 0xbe, 0x56, 0xd6, 0x32, 0xbd, 0x0e, 0x67, 0xa5, 0x22, 0x6b, 0x02, 0xb9, 0xb9, 0xb4,
	0xc5, 0x12, 0x17, 0x9f, 0x1c, 0x1e, 0x37, 0x96, 0x7d, 0x76, 0xf3, 0x0a, 0x76, 0x63, 0xa5, 0xa7,
	0x83, 0x61, 0xc6, 0x76, 0x0f, 0xa4, 0xa5, 0x9b, 0x70, 0xd2, 0xfa, 0x8d, 0xa9, 0x20, 0x32, 0xf9,
	0x7b, 0xf8, 0xed, 0xad, 0x0e, 0xbf, 0xdd, 0xa6, 0xa2, 0x9d, 0xbf, 0x4b, 0xe1, 0xfa, 0x81, 0x9c,
	0x1a, 0xe2, 0x53, 0xa5, 0x4d, 0x69, 0x82, 0x41, 0xcf, 0x82, 0xb1, 0x74, 0x0b, 0x4e, 0x77, 0x77,
	0x41, 0x51, 0x53, 0x3c, 0x5d, 0x95, 0x1d, 0xf2, 0xf5, 0xc3, 0xa7, 0x88, 0x77, 0xff, 0xb1, 0xf2,
	0x28, 0x3a, 0xf9, 0x3f, 0x26, 0x7a, 0x9d, 0xd2, 0x3d, 0x35, 0x9c, 0x84, 0x89, 0x5e, 0x17, 0xc1,
	0x74, 0xb3, 0x51, 0x9c, 0xb7, 0xc6, 0x0e, 0xcf, 0xcc, 0x50, 0x64, 0xf9, 0x09, 0xec, 0x2f, 0xec,
	0x4f, 0x43, 0xd7, 0xcd, 0x88, 0xdd, 0x34, 0xb0, 0xea, 0x37, 0x61, 0x8d, 0xa6, 0xe3, 0x99, 0x9b,
	0x2d, 0x37, 0x13, 0x12, 0xfc, 0xdb, 0xf0, 0x0c, 0x2d, 0xa6, 0x8b, 0x6d, 0x42, 0x62, 0x11, 0x4c,
	0xed, 0xea, 0x2b, 0x55, 0x96, 0x13, 0x90, 0x5c, 0xba, 0x27, 0x2a, 0x2c, 0x4c, 0x53, 0xcd, 0xc1,
	0x58, 0xdb, 0x52, 0xb9, 0x21, 0xce, 0xb1, 0xce, 0xf1, 0x5f, 0x3e, 0x7e, 0x3e, 0xcc, 0x3e, 0x7d,
	0x3e, 0xcc, 0x7e, 0xf8, 0x7c, 0x98, 0x7d, 0xfd, 0xe5, 0xb0, 0xf5, 0xe9, 0xcb, 0x61, 0xeb, 0xfb,
	0x2f, 0x87, 0xad, 0xff, 0xec, 0x4f, 0xff, 0xea, 0x3e, 0xcc, 0xfe, 0xef, 0xf8, 0x6e, 0xf0, 0x83,
	0x5e, 0xfc, 0x75, 0xfb, 0xeb, 0x4f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x5f, 0x39, 0x96, 0xff,
	0x09, 0x00, 0x00,
}
