// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: structs/structs/planet.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Planet struct {
	Id                string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MaxOre            uint64       `protobuf:"varint,2,opt,name=maxOre,proto3" json:"maxOre,omitempty"`
	Creator           string       `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	Owner             string       `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Space             []string     `protobuf:"bytes,5,rep,name=space,proto3" json:"space,omitempty"`
	Air               []string     `protobuf:"bytes,6,rep,name=air,proto3" json:"air,omitempty"`
	Land              []string     `protobuf:"bytes,7,rep,name=land,proto3" json:"land,omitempty"`
	Water             []string     `protobuf:"bytes,8,rep,name=water,proto3" json:"water,omitempty"`
	SpaceSlots        uint64       `protobuf:"varint,9,opt,name=spaceSlots,proto3" json:"spaceSlots,omitempty"`
	AirSlots          uint64       `protobuf:"varint,10,opt,name=airSlots,proto3" json:"airSlots,omitempty"`
	LandSlots         uint64       `protobuf:"varint,11,opt,name=landSlots,proto3" json:"landSlots,omitempty"`
	WaterSlots        uint64       `protobuf:"varint,12,opt,name=waterSlots,proto3" json:"waterSlots,omitempty"`
	Status            PlanetStatus `protobuf:"varint,13,opt,name=status,proto3,enum=structs.structs.PlanetStatus" json:"status,omitempty"`
	LocationListStart string       `protobuf:"bytes,14,opt,name=locationListStart,proto3" json:"locationListStart,omitempty"`
	LocationListLast  string       `protobuf:"bytes,15,opt,name=locationListLast,proto3" json:"locationListLast,omitempty"`
}

func (m *Planet) Reset()         { *m = Planet{} }
func (m *Planet) String() string { return proto.CompactTextString(m) }
func (*Planet) ProtoMessage()    {}
func (*Planet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d6079b21199cebc, []int{0}
}
func (m *Planet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Planet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Planet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Planet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Planet.Merge(m, src)
}
func (m *Planet) XXX_Size() int {
	return m.Size()
}
func (m *Planet) XXX_DiscardUnknown() {
	xxx_messageInfo_Planet.DiscardUnknown(m)
}

var xxx_messageInfo_Planet proto.InternalMessageInfo

func (m *Planet) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Planet) GetMaxOre() uint64 {
	if m != nil {
		return m.MaxOre
	}
	return 0
}

func (m *Planet) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Planet) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Planet) GetSpace() []string {
	if m != nil {
		return m.Space
	}
	return nil
}

func (m *Planet) GetAir() []string {
	if m != nil {
		return m.Air
	}
	return nil
}

func (m *Planet) GetLand() []string {
	if m != nil {
		return m.Land
	}
	return nil
}

func (m *Planet) GetWater() []string {
	if m != nil {
		return m.Water
	}
	return nil
}

func (m *Planet) GetSpaceSlots() uint64 {
	if m != nil {
		return m.SpaceSlots
	}
	return 0
}

func (m *Planet) GetAirSlots() uint64 {
	if m != nil {
		return m.AirSlots
	}
	return 0
}

func (m *Planet) GetLandSlots() uint64 {
	if m != nil {
		return m.LandSlots
	}
	return 0
}

func (m *Planet) GetWaterSlots() uint64 {
	if m != nil {
		return m.WaterSlots
	}
	return 0
}

func (m *Planet) GetStatus() PlanetStatus {
	if m != nil {
		return m.Status
	}
	return PlanetStatus_active
}

func (m *Planet) GetLocationListStart() string {
	if m != nil {
		return m.LocationListStart
	}
	return ""
}

func (m *Planet) GetLocationListLast() string {
	if m != nil {
		return m.LocationListLast
	}
	return ""
}

type PlanetAttributeRecord struct {
	AttributeId string `protobuf:"bytes,1,opt,name=attributeId,proto3" json:"attributeId,omitempty"`
	Value       uint64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PlanetAttributeRecord) Reset()         { *m = PlanetAttributeRecord{} }
func (m *PlanetAttributeRecord) String() string { return proto.CompactTextString(m) }
func (*PlanetAttributeRecord) ProtoMessage()    {}
func (*PlanetAttributeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d6079b21199cebc, []int{1}
}
func (m *PlanetAttributeRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlanetAttributeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlanetAttributeRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlanetAttributeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetAttributeRecord.Merge(m, src)
}
func (m *PlanetAttributeRecord) XXX_Size() int {
	return m.Size()
}
func (m *PlanetAttributeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetAttributeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetAttributeRecord proto.InternalMessageInfo

func (m *PlanetAttributeRecord) GetAttributeId() string {
	if m != nil {
		return m.AttributeId
	}
	return ""
}

func (m *PlanetAttributeRecord) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PlanetAttributes struct {
	PlanetaryShield                                            uint64 `protobuf:"varint,1,opt,name=planetaryShield,proto3" json:"planetaryShield,omitempty"`
	RepairNetworkQuantity                                      uint64 `protobuf:"varint,2,opt,name=repairNetworkQuantity,proto3" json:"repairNetworkQuantity,omitempty"`
	DefensiveCannonQuantity                                    uint64 `protobuf:"varint,3,opt,name=defensiveCannonQuantity,proto3" json:"defensiveCannonQuantity,omitempty"`
	CoordinatedGlobalShieldNetworkQuantity                     uint64 `protobuf:"varint,4,opt,name=coordinatedGlobalShieldNetworkQuantity,proto3" json:"coordinatedGlobalShieldNetworkQuantity,omitempty"`
	LowOrbitBallisticsInterceptorNetworkQuantity               uint64 `protobuf:"varint,5,opt,name=lowOrbitBallisticsInterceptorNetworkQuantity,proto3" json:"lowOrbitBallisticsInterceptorNetworkQuantity,omitempty"`
	AdvancedLowOrbitBallisticsInterceptorNetworkQuantity       uint64 `protobuf:"varint,6,opt,name=advancedLowOrbitBallisticsInterceptorNetworkQuantity,proto3" json:"advancedLowOrbitBallisticsInterceptorNetworkQuantity,omitempty"`
	LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator   uint64 `protobuf:"varint,7,opt,name=lowOrbitBallisticsInterceptorNetworkSuccessRateNumerator,proto3" json:"lowOrbitBallisticsInterceptorNetworkSuccessRateNumerator,omitempty"`
	LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator uint64 `protobuf:"varint,8,opt,name=lowOrbitBallisticsInterceptorNetworkSuccessRateDenominator,proto3" json:"lowOrbitBallisticsInterceptorNetworkSuccessRateDenominator,omitempty"`
	OrbitalJammingStationQuantity                              uint64 `protobuf:"varint,9,opt,name=orbitalJammingStationQuantity,proto3" json:"orbitalJammingStationQuantity,omitempty"`
	AdvancedOrbitalJammingStationQuantity                      uint64 `protobuf:"varint,10,opt,name=advancedOrbitalJammingStationQuantity,proto3" json:"advancedOrbitalJammingStationQuantity,omitempty"`
	BlockStartRaid                                             uint64 `protobuf:"varint,11,opt,name=blockStartRaid,proto3" json:"blockStartRaid,omitempty"`
}

func (m *PlanetAttributes) Reset()         { *m = PlanetAttributes{} }
func (m *PlanetAttributes) String() string { return proto.CompactTextString(m) }
func (*PlanetAttributes) ProtoMessage()    {}
func (*PlanetAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d6079b21199cebc, []int{2}
}
func (m *PlanetAttributes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlanetAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlanetAttributes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlanetAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanetAttributes.Merge(m, src)
}
func (m *PlanetAttributes) XXX_Size() int {
	return m.Size()
}
func (m *PlanetAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanetAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_PlanetAttributes proto.InternalMessageInfo

func (m *PlanetAttributes) GetPlanetaryShield() uint64 {
	if m != nil {
		return m.PlanetaryShield
	}
	return 0
}

func (m *PlanetAttributes) GetRepairNetworkQuantity() uint64 {
	if m != nil {
		return m.RepairNetworkQuantity
	}
	return 0
}

func (m *PlanetAttributes) GetDefensiveCannonQuantity() uint64 {
	if m != nil {
		return m.DefensiveCannonQuantity
	}
	return 0
}

func (m *PlanetAttributes) GetCoordinatedGlobalShieldNetworkQuantity() uint64 {
	if m != nil {
		return m.CoordinatedGlobalShieldNetworkQuantity
	}
	return 0
}

func (m *PlanetAttributes) GetLowOrbitBallisticsInterceptorNetworkQuantity() uint64 {
	if m != nil {
		return m.LowOrbitBallisticsInterceptorNetworkQuantity
	}
	return 0
}

func (m *PlanetAttributes) GetAdvancedLowOrbitBallisticsInterceptorNetworkQuantity() uint64 {
	if m != nil {
		return m.AdvancedLowOrbitBallisticsInterceptorNetworkQuantity
	}
	return 0
}

func (m *PlanetAttributes) GetLowOrbitBallisticsInterceptorNetworkSuccessRateNumerator() uint64 {
	if m != nil {
		return m.LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator
	}
	return 0
}

func (m *PlanetAttributes) GetLowOrbitBallisticsInterceptorNetworkSuccessRateDenominator() uint64 {
	if m != nil {
		return m.LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator
	}
	return 0
}

func (m *PlanetAttributes) GetOrbitalJammingStationQuantity() uint64 {
	if m != nil {
		return m.OrbitalJammingStationQuantity
	}
	return 0
}

func (m *PlanetAttributes) GetAdvancedOrbitalJammingStationQuantity() uint64 {
	if m != nil {
		return m.AdvancedOrbitalJammingStationQuantity
	}
	return 0
}

func (m *PlanetAttributes) GetBlockStartRaid() uint64 {
	if m != nil {
		return m.BlockStartRaid
	}
	return 0
}

func init() {
	proto.RegisterType((*Planet)(nil), "structs.structs.Planet")
	proto.RegisterType((*PlanetAttributeRecord)(nil), "structs.structs.PlanetAttributeRecord")
	proto.RegisterType((*PlanetAttributes)(nil), "structs.structs.PlanetAttributes")
}

func init() { proto.RegisterFile("structs/structs/planet.proto", fileDescriptor_6d6079b21199cebc) }

var fileDescriptor_6d6079b21199cebc = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x4e, 0x13, 0x5f,
	0x14, 0x66, 0xe8, 0x3f, 0x38, 0xfc, 0x7e, 0x05, 0x4e, 0x44, 0x26, 0x0d, 0x4c, 0x1a, 0x12, 0x49,
	0x43, 0x48, 0x89, 0xca, 0x82, 0x18, 0x37, 0x22, 0x89, 0xc1, 0x10, 0xaa, 0x53, 0xe3, 0xc2, 0xdd,
	0xe9, 0xcc, 0x55, 0x6f, 0x98, 0xde, 0xdb, 0xdc, 0x7b, 0x87, 0x52, 0x17, 0x3e, 0x83, 0x0f, 0xe0,
	0x03, 0xb8, 0xf4, 0x21, 0x5c, 0xb8, 0x64, 0xe9, 0xd2, 0xc0, 0xc2, 0xd7, 0x30, 0x73, 0x6f, 0x07,
	0x9a, 0xa2, 0x84, 0xe2, 0xa6, 0x33, 0xe7, 0x3b, 0xdf, 0xf7, 0x9d, 0x3b, 0xe7, 0x74, 0xce, 0xc0,
	0x8a, 0x36, 0x2a, 0x8d, 0x8c, 0xde, 0xca, 0xaf, 0xbd, 0x84, 0x04, 0x33, 0xcd, 0x9e, 0x92, 0x46,
	0xe2, 0xfc, 0x10, 0x6d, 0x0e, 0xaf, 0xb5, 0xda, 0x38, 0xfd, 0x88, 0x0d, 0xb4, 0x23, 0xd7, 0x16,
	0xa9, 0xcb, 0x85, 0xdc, 0xb2, 0xbf, 0x0e, 0x5a, 0xfb, 0x56, 0x80, 0xf2, 0x0b, 0x6b, 0x88, 0x55,
	0x98, 0xe6, 0xb1, 0xef, 0xd5, 0xbd, 0xc6, 0x6c, 0x38, 0xcd, 0x63, 0xbc, 0x0b, 0xe5, 0x2e, 0x9d,
	0xb4, 0x14, 0xf3, 0xa7, 0xeb, 0x5e, 0xa3, 0x18, 0x0e, 0x23, 0xf4, 0xa1, 0x12, 0x29, 0x46, 0x46,
	0x2a, 0xbf, 0x60, 0xc9, 0x79, 0x88, 0x77, 0xa0, 0x24, 0xfb, 0x82, 0x29, 0xbf, 0x68, 0x71, 0x17,
	0x64, 0xa8, 0xee, 0x51, 0xc4, 0xfc, 0x52, 0xbd, 0x90, 0xa1, 0x36, 0xc0, 0x05, 0x28, 0x10, 0x57,
	0x7e, 0xd9, 0x62, 0xd9, 0x2d, 0x22, 0x14, 0x13, 0x12, 0xb1, 0x5f, 0xb1, 0x90, 0xbd, 0xcf, 0xb4,
	0x7d, 0x32, 0x4c, 0xf9, 0x33, 0x4e, 0x6b, 0x03, 0x0c, 0x00, 0xac, 0x49, 0x3b, 0x91, 0x46, 0xfb,
	0xb3, 0xf6, 0x74, 0x23, 0x08, 0xd6, 0x60, 0x86, 0xb8, 0x72, 0x59, 0xb0, 0xd9, 0x8b, 0x18, 0x57,
	0x60, 0x36, 0x73, 0x76, 0xc9, 0x39, 0x9b, 0xbc, 0x04, 0x32, 0x67, 0x5b, 0xc2, 0xa5, 0xff, 0x73,
	0xce, 0x97, 0x08, 0x3e, 0x86, 0xb2, 0x36, 0x64, 0x52, 0xed, 0xff, 0x5f, 0xf7, 0x1a, 0xd5, 0x07,
	0xab, 0xcd, 0xb1, 0xfe, 0x37, 0xdd, 0x74, 0xda, 0x96, 0xb4, 0x5b, 0xfa, 0xf2, 0xeb, 0xeb, 0x86,
	0x17, 0x0e, 0x35, 0xb8, 0x09, 0x8b, 0x89, 0x8c, 0xc8, 0x70, 0x29, 0x0e, 0xb8, 0xce, 0x48, 0xca,
	0xf8, 0x55, 0xdb, 0xab, 0xab, 0x09, 0xdc, 0x80, 0x85, 0x51, 0xf0, 0x80, 0xb4, 0xf1, 0xe7, 0x2d,
	0xf9, 0x0a, 0xbe, 0xd6, 0x82, 0x25, 0x37, 0xc5, 0x27, 0xc6, 0x28, 0xde, 0x49, 0x0d, 0x0b, 0x59,
	0x24, 0x55, 0x8c, 0x75, 0x98, 0xa3, 0x1c, 0xda, 0xcf, 0xa7, 0x3b, 0x0a, 0x65, 0x2d, 0x3e, 0xa6,
	0x24, 0xcd, 0xa7, 0xec, 0x82, 0xb5, 0xcf, 0x15, 0x58, 0x18, 0x73, 0xd4, 0xd8, 0x80, 0x79, 0xf7,
	0x78, 0xa4, 0x06, 0xed, 0xf7, 0x9c, 0x25, 0xce, 0xb0, 0x18, 0x8e, 0xc3, 0xb8, 0x0d, 0x4b, 0x8a,
	0xf5, 0x88, 0xab, 0x43, 0x66, 0xfa, 0x52, 0x1d, 0xbd, 0x4c, 0x49, 0x18, 0x6e, 0x06, 0xc3, 0x22,
	0x7f, 0x4e, 0xe2, 0x0e, 0x2c, 0xc7, 0xec, 0x2d, 0x13, 0x9a, 0x1f, 0xb3, 0xa7, 0x24, 0x84, 0x14,
	0x17, 0xba, 0x82, 0xd5, 0xfd, 0x2d, 0x8d, 0xaf, 0x61, 0x3d, 0x92, 0x52, 0xc5, 0x5c, 0x90, 0x61,
	0xf1, 0xb3, 0x44, 0x76, 0x28, 0x71, 0x47, 0x19, 0x3f, 0x40, 0xd1, 0x1a, 0xdd, 0x90, 0x8d, 0x1d,
	0xd8, 0x4c, 0x64, 0xbf, 0xa5, 0x3a, 0xdc, 0xec, 0x52, 0x92, 0x70, 0x6d, 0x78, 0xa4, 0xf7, 0x85,
	0x61, 0x2a, 0x62, 0x3d, 0x23, 0xaf, 0x3c, 0x5e, 0xc9, 0xba, 0x4f, 0xa4, 0x41, 0x05, 0xdb, 0x14,
	0x1f, 0x93, 0x88, 0x58, 0x7c, 0x30, 0x49, 0xad, 0xb2, 0xad, 0x75, 0x2b, 0x2d, 0x7e, 0x80, 0x9d,
	0x9b, 0x9c, 0xb1, 0x9d, 0x46, 0x11, 0xd3, 0x3a, 0x24, 0xc3, 0x0e, 0xd3, 0x2e, 0x53, 0xf6, 0xa5,
	0xaf, 0xd8, 0xba, 0xb7, 0xd6, 0xe3, 0x47, 0x78, 0x34, 0xa1, 0x76, 0x8f, 0x09, 0xd9, 0xcd, 0x86,
	0x25, 0xb3, 0x45, 0x90, 0x55, 0xff, 0x07, 0x07, 0xdc, 0x83, 0x55, 0x99, 0x49, 0x29, 0x79, 0x4e,
	0xdd, 0x2e, 0x17, 0xef, 0xb2, 0x97, 0x95, 0x8f, 0xfc, 0xd7, 0xdc, 0x42, 0xb9, 0x9e, 0x84, 0xaf,
	0xe0, 0x5e, 0xde, 0xf9, 0xd6, 0xb5, 0x6e, 0x6e, 0x01, 0xdd, 0x8c, 0x8c, 0xeb, 0x50, 0xed, 0x24,
	0x32, 0x3a, 0xb2, 0x1b, 0x20, 0x24, 0x1e, 0x0f, 0x57, 0xd4, 0x18, 0xba, 0x7b, 0xff, 0xfb, 0x59,
	0xe0, 0x9d, 0x9e, 0x05, 0xde, 0xcf, 0xb3, 0xc0, 0xfb, 0x74, 0x1e, 0x4c, 0x9d, 0x9e, 0x07, 0x53,
	0x3f, 0xce, 0x83, 0xa9, 0x37, 0xcb, 0xf9, 0xde, 0x3f, 0xb9, 0xf8, 0x02, 0x98, 0x41, 0x8f, 0xe9,
	0x4e, 0xd9, 0x2e, 0xfc, 0x87, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x95, 0x83, 0x37, 0x8d, 0x50,
	0x06, 0x00, 0x00,
}

func (m *Planet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Planet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Planet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LocationListLast) > 0 {
		i -= len(m.LocationListLast)
		copy(dAtA[i:], m.LocationListLast)
		i = encodeVarintPlanet(dAtA, i, uint64(len(m.LocationListLast)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.LocationListStart) > 0 {
		i -= len(m.LocationListStart)
		copy(dAtA[i:], m.LocationListStart)
		i = encodeVarintPlanet(dAtA, i, uint64(len(m.LocationListStart)))
		i--
		dAtA[i] = 0x72
	}
	if m.Status != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x68
	}
	if m.WaterSlots != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.WaterSlots))
		i--
		dAtA[i] = 0x60
	}
	if m.LandSlots != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.LandSlots))
		i--
		dAtA[i] = 0x58
	}
	if m.AirSlots != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.AirSlots))
		i--
		dAtA[i] = 0x50
	}
	if m.SpaceSlots != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.SpaceSlots))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Water) > 0 {
		for iNdEx := len(m.Water) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Water[iNdEx])
			copy(dAtA[i:], m.Water[iNdEx])
			i = encodeVarintPlanet(dAtA, i, uint64(len(m.Water[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Land) > 0 {
		for iNdEx := len(m.Land) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Land[iNdEx])
			copy(dAtA[i:], m.Land[iNdEx])
			i = encodeVarintPlanet(dAtA, i, uint64(len(m.Land[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Air) > 0 {
		for iNdEx := len(m.Air) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Air[iNdEx])
			copy(dAtA[i:], m.Air[iNdEx])
			i = encodeVarintPlanet(dAtA, i, uint64(len(m.Air[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Space) > 0 {
		for iNdEx := len(m.Space) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Space[iNdEx])
			copy(dAtA[i:], m.Space[iNdEx])
			i = encodeVarintPlanet(dAtA, i, uint64(len(m.Space[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintPlanet(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPlanet(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MaxOre != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.MaxOre))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintPlanet(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PlanetAttributeRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlanetAttributeRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlanetAttributeRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x10
	}
	if len(m.AttributeId) > 0 {
		i -= len(m.AttributeId)
		copy(dAtA[i:], m.AttributeId)
		i = encodeVarintPlanet(dAtA, i, uint64(len(m.AttributeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PlanetAttributes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlanetAttributes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlanetAttributes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockStartRaid != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.BlockStartRaid))
		i--
		dAtA[i] = 0x58
	}
	if m.AdvancedOrbitalJammingStationQuantity != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.AdvancedOrbitalJammingStationQuantity))
		i--
		dAtA[i] = 0x50
	}
	if m.OrbitalJammingStationQuantity != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.OrbitalJammingStationQuantity))
		i--
		dAtA[i] = 0x48
	}
	if m.LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator))
		i--
		dAtA[i] = 0x40
	}
	if m.LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator))
		i--
		dAtA[i] = 0x38
	}
	if m.AdvancedLowOrbitBallisticsInterceptorNetworkQuantity != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.AdvancedLowOrbitBallisticsInterceptorNetworkQuantity))
		i--
		dAtA[i] = 0x30
	}
	if m.LowOrbitBallisticsInterceptorNetworkQuantity != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.LowOrbitBallisticsInterceptorNetworkQuantity))
		i--
		dAtA[i] = 0x28
	}
	if m.CoordinatedGlobalShieldNetworkQuantity != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.CoordinatedGlobalShieldNetworkQuantity))
		i--
		dAtA[i] = 0x20
	}
	if m.DefensiveCannonQuantity != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.DefensiveCannonQuantity))
		i--
		dAtA[i] = 0x18
	}
	if m.RepairNetworkQuantity != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.RepairNetworkQuantity))
		i--
		dAtA[i] = 0x10
	}
	if m.PlanetaryShield != 0 {
		i = encodeVarintPlanet(dAtA, i, uint64(m.PlanetaryShield))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPlanet(dAtA []byte, offset int, v uint64) int {
	offset -= sovPlanet(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Planet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovPlanet(uint64(l))
	}
	if m.MaxOre != 0 {
		n += 1 + sovPlanet(uint64(m.MaxOre))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPlanet(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovPlanet(uint64(l))
	}
	if len(m.Space) > 0 {
		for _, s := range m.Space {
			l = len(s)
			n += 1 + l + sovPlanet(uint64(l))
		}
	}
	if len(m.Air) > 0 {
		for _, s := range m.Air {
			l = len(s)
			n += 1 + l + sovPlanet(uint64(l))
		}
	}
	if len(m.Land) > 0 {
		for _, s := range m.Land {
			l = len(s)
			n += 1 + l + sovPlanet(uint64(l))
		}
	}
	if len(m.Water) > 0 {
		for _, s := range m.Water {
			l = len(s)
			n += 1 + l + sovPlanet(uint64(l))
		}
	}
	if m.SpaceSlots != 0 {
		n += 1 + sovPlanet(uint64(m.SpaceSlots))
	}
	if m.AirSlots != 0 {
		n += 1 + sovPlanet(uint64(m.AirSlots))
	}
	if m.LandSlots != 0 {
		n += 1 + sovPlanet(uint64(m.LandSlots))
	}
	if m.WaterSlots != 0 {
		n += 1 + sovPlanet(uint64(m.WaterSlots))
	}
	if m.Status != 0 {
		n += 1 + sovPlanet(uint64(m.Status))
	}
	l = len(m.LocationListStart)
	if l > 0 {
		n += 1 + l + sovPlanet(uint64(l))
	}
	l = len(m.LocationListLast)
	if l > 0 {
		n += 1 + l + sovPlanet(uint64(l))
	}
	return n
}

func (m *PlanetAttributeRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AttributeId)
	if l > 0 {
		n += 1 + l + sovPlanet(uint64(l))
	}
	if m.Value != 0 {
		n += 1 + sovPlanet(uint64(m.Value))
	}
	return n
}

func (m *PlanetAttributes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PlanetaryShield != 0 {
		n += 1 + sovPlanet(uint64(m.PlanetaryShield))
	}
	if m.RepairNetworkQuantity != 0 {
		n += 1 + sovPlanet(uint64(m.RepairNetworkQuantity))
	}
	if m.DefensiveCannonQuantity != 0 {
		n += 1 + sovPlanet(uint64(m.DefensiveCannonQuantity))
	}
	if m.CoordinatedGlobalShieldNetworkQuantity != 0 {
		n += 1 + sovPlanet(uint64(m.CoordinatedGlobalShieldNetworkQuantity))
	}
	if m.LowOrbitBallisticsInterceptorNetworkQuantity != 0 {
		n += 1 + sovPlanet(uint64(m.LowOrbitBallisticsInterceptorNetworkQuantity))
	}
	if m.AdvancedLowOrbitBallisticsInterceptorNetworkQuantity != 0 {
		n += 1 + sovPlanet(uint64(m.AdvancedLowOrbitBallisticsInterceptorNetworkQuantity))
	}
	if m.LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator != 0 {
		n += 1 + sovPlanet(uint64(m.LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator))
	}
	if m.LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator != 0 {
		n += 1 + sovPlanet(uint64(m.LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator))
	}
	if m.OrbitalJammingStationQuantity != 0 {
		n += 1 + sovPlanet(uint64(m.OrbitalJammingStationQuantity))
	}
	if m.AdvancedOrbitalJammingStationQuantity != 0 {
		n += 1 + sovPlanet(uint64(m.AdvancedOrbitalJammingStationQuantity))
	}
	if m.BlockStartRaid != 0 {
		n += 1 + sovPlanet(uint64(m.BlockStartRaid))
	}
	return n
}

func sovPlanet(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPlanet(x uint64) (n int) {
	return sovPlanet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Planet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Planet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Planet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOre", wireType)
			}
			m.MaxOre = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOre |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Space", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Space = append(m.Space, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Air", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Air = append(m.Air, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Land", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Land = append(m.Land, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Water", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Water = append(m.Water, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpaceSlots", wireType)
			}
			m.SpaceSlots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SpaceSlots |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirSlots", wireType)
			}
			m.AirSlots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AirSlots |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LandSlots", wireType)
			}
			m.LandSlots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LandSlots |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WaterSlots", wireType)
			}
			m.WaterSlots = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WaterSlots |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PlanetStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocationListStart", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LocationListStart = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocationListLast", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LocationListLast = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPlanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlanetAttributeRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlanetAttributeRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlanetAttributeRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttributeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlanet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlanet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttributeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPlanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPlanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlanetAttributes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlanet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlanetAttributes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlanetAttributes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanetaryShield", wireType)
			}
			m.PlanetaryShield = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlanetaryShield |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepairNetworkQuantity", wireType)
			}
			m.RepairNetworkQuantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RepairNetworkQuantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefensiveCannonQuantity", wireType)
			}
			m.DefensiveCannonQuantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefensiveCannonQuantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoordinatedGlobalShieldNetworkQuantity", wireType)
			}
			m.CoordinatedGlobalShieldNetworkQuantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoordinatedGlobalShieldNetworkQuantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowOrbitBallisticsInterceptorNetworkQuantity", wireType)
			}
			m.LowOrbitBallisticsInterceptorNetworkQuantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LowOrbitBallisticsInterceptorNetworkQuantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdvancedLowOrbitBallisticsInterceptorNetworkQuantity", wireType)
			}
			m.AdvancedLowOrbitBallisticsInterceptorNetworkQuantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AdvancedLowOrbitBallisticsInterceptorNetworkQuantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator", wireType)
			}
			m.LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LowOrbitBallisticsInterceptorNetworkSuccessRateNumerator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator", wireType)
			}
			m.LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LowOrbitBallisticsInterceptorNetworkSuccessRateDenominator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrbitalJammingStationQuantity", wireType)
			}
			m.OrbitalJammingStationQuantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrbitalJammingStationQuantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdvancedOrbitalJammingStationQuantity", wireType)
			}
			m.AdvancedOrbitalJammingStationQuantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AdvancedOrbitalJammingStationQuantity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockStartRaid", wireType)
			}
			m.BlockStartRaid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockStartRaid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPlanet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPlanet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPlanet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPlanet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlanet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPlanet
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPlanet
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPlanet
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPlanet        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPlanet          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPlanet = fmt.Errorf("proto: unexpected end of group")
)
