// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: structs/structs/player.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	Id                string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index             uint64     `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	GuildId           string     `protobuf:"bytes,3,opt,name=guildId,proto3" json:"guildId,omitempty"`
	SubstationId      string     `protobuf:"bytes,4,opt,name=substationId,proto3" json:"substationId,omitempty"`
	Creator           string     `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	PrimaryAddress    string     `protobuf:"bytes,6,opt,name=primaryAddress,proto3" json:"primaryAddress,omitempty"`
	PlanetId          string     `protobuf:"bytes,7,opt,name=planetId,proto3" json:"planetId,omitempty"`
	FleetId           string     `protobuf:"bytes,8,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	Load              uint64     `protobuf:"varint,9,opt,name=load,proto3" json:"load,omitempty"`
	Capacity          uint64     `protobuf:"varint,10,opt,name=capacity,proto3" json:"capacity,omitempty"`
	CapacitySecondary uint64     `protobuf:"varint,11,opt,name=capacitySecondary,proto3" json:"capacitySecondary,omitempty"`
	StructsLoad       uint64     `protobuf:"varint,12,opt,name=structsLoad,proto3" json:"structsLoad,omitempty"`
	Storage           types.Coin `protobuf:"bytes,13,opt,name=storage,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"storage"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca9c11ebc41e4761, []int{0}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Player.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return m.Size()
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Player) GetGuildId() string {
	if m != nil {
		return m.GuildId
	}
	return ""
}

func (m *Player) GetSubstationId() string {
	if m != nil {
		return m.SubstationId
	}
	return ""
}

func (m *Player) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Player) GetPrimaryAddress() string {
	if m != nil {
		return m.PrimaryAddress
	}
	return ""
}

func (m *Player) GetPlanetId() string {
	if m != nil {
		return m.PlanetId
	}
	return ""
}

func (m *Player) GetFleetId() string {
	if m != nil {
		return m.FleetId
	}
	return ""
}

func (m *Player) GetLoad() uint64 {
	if m != nil {
		return m.Load
	}
	return 0
}

func (m *Player) GetCapacity() uint64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Player) GetCapacitySecondary() uint64 {
	if m != nil {
		return m.CapacitySecondary
	}
	return 0
}

func (m *Player) GetStructsLoad() uint64 {
	if m != nil {
		return m.StructsLoad
	}
	return 0
}

func (m *Player) GetStorage() types.Coin {
	if m != nil {
		return m.Storage
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Player)(nil), "structs.structs.Player")
}

func init() { proto.RegisterFile("structs/structs/player.proto", fileDescriptor_ca9c11ebc41e4761) }

var fileDescriptor_ca9c11ebc41e4761 = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0xae, 0xd3, 0x30,
	0x10, 0x4e, 0xfa, 0xfa, 0xda, 0xf7, 0xdc, 0x47, 0x11, 0x56, 0x25, 0xdc, 0x0a, 0xa5, 0x51, 0x57,
	0x59, 0xd0, 0x84, 0xc2, 0x05, 0xa0, 0xac, 0x2a, 0xb1, 0x40, 0xe9, 0x8e, 0x0d, 0x72, 0x6c, 0x13,
	0x2c, 0xd2, 0x38, 0xb2, 0x1d, 0xd4, 0xdc, 0x82, 0x73, 0xb0, 0xe6, 0x10, 0x5d, 0x56, 0xac, 0x58,
	0x01, 0x6a, 0xc5, 0x3d, 0x50, 0x6c, 0xa7, 0xe2, 0x67, 0x35, 0xf3, 0xfd, 0xcc, 0x8c, 0x46, 0x33,
	0xe0, 0x91, 0xd2, 0xb2, 0x26, 0x5a, 0x25, 0x5d, 0xac, 0x0a, 0xdc, 0x30, 0x19, 0x57, 0x52, 0x68,
	0x01, 0xef, 0x3b, 0x36, 0x76, 0x71, 0x16, 0x10, 0xa1, 0x76, 0x42, 0x25, 0x19, 0x56, 0x2c, 0xf9,
	0xb8, 0xca, 0x98, 0xc6, 0xab, 0x84, 0x08, 0x5e, 0xda, 0x82, 0xd9, 0xd4, 0xea, 0x6f, 0x0d, 0x4a,
	0x2c, 0x70, 0xd2, 0x24, 0x17, 0xb9, 0xb0, 0x7c, 0x9b, 0x59, 0x76, 0xf1, 0xeb, 0x0a, 0x0c, 0x5e,
	0x9b, 0x91, 0x70, 0x0c, 0x7a, 0x9c, 0x22, 0x3f, 0xf4, 0xa3, 0xdb, 0xb4, 0xc7, 0x29, 0x9c, 0x80,
	0x6b, 0x5e, 0x52, 0xb6, 0x47, 0xbd, 0xd0, 0x8f, 0xfa, 0xa9, 0x05, 0x10, 0x81, 0x61, 0x5e, 0xf3,
	0x82, 0x6e, 0x28, 0xba, 0x32, 0xd6, 0x0e, 0xc2, 0x05, 0xb8, 0x53, 0x75, 0xa6, 0x34, 0xd6, 0x5c,
	0x94, 0x1b, 0x8a, 0xfa, 0x46, 0xfe, 0x8b, 0x6b, 0xab, 0x89, 0x64, 0x58, 0x0b, 0x89, 0xae, 0x6d,
	0xb5, 0x83, 0xf0, 0x39, 0x18, 0x57, 0x92, 0xef, 0xb0, 0x6c, 0x5e, 0x50, 0x2a, 0x99, 0x52, 0x68,
	0xd0, 0x1a, 0xd6, 0xe8, 0xeb, 0x97, 0xe5, 0xc4, 0x2d, 0xe2, 0x94, 0xad, 0x96, 0xbc, 0xcc, 0xd3,
	0x7f, 0xfc, 0x70, 0x06, 0x6e, 0xaa, 0x02, 0x97, 0x4c, 0x6f, 0x28, 0x1a, 0x9a, 0xe6, 0x17, 0xdc,
	0xce, 0x7d, 0x57, 0x30, 0x23, 0xdd, 0xd8, 0xb9, 0x0e, 0x42, 0x08, 0xfa, 0x85, 0xc0, 0x14, 0xdd,
	0x9a, 0x25, 0x4d, 0xde, 0x76, 0x22, 0xb8, 0xc2, 0x84, 0xeb, 0x06, 0x01, 0xc3, 0x5f, 0x30, 0x7c,
	0x0c, 0x1e, 0x74, 0xf9, 0x96, 0x11, 0x51, 0x52, 0x2c, 0x1b, 0x34, 0x32, 0xa6, 0xff, 0x05, 0x18,
	0x82, 0x91, 0x3b, 0xdd, 0xab, 0x76, 0xc8, 0x9d, 0xf1, 0xfd, 0x49, 0x41, 0x06, 0x86, 0x4a, 0x0b,
	0x89, 0x73, 0x86, 0xee, 0x85, 0x7e, 0x34, 0x7a, 0x3a, 0x8d, 0xdd, 0xb6, 0xed, 0x8d, 0x63, 0x77,
	0xe3, 0xf8, 0xa5, 0xe0, 0xe5, 0xfa, 0xc9, 0xe1, 0xfb, 0xdc, 0xfb, 0xfc, 0x63, 0x1e, 0xe5, 0x5c,
	0xbf, 0xaf, 0xb3, 0x98, 0x88, 0x9d, 0xbb, 0xb1, 0x0b, 0x4b, 0x45, 0x3f, 0x24, 0xba, 0xa9, 0x98,
	0x32, 0x05, 0x2a, 0xed, 0x7a, 0xaf, 0x57, 0x87, 0x53, 0xe0, 0x1f, 0x4f, 0x81, 0xff, 0xf3, 0x14,
	0xf8, 0x9f, 0xce, 0x81, 0x77, 0x3c, 0x07, 0xde, 0xb7, 0x73, 0xe0, 0xbd, 0x79, 0xd8, 0x7d, 0xde,
	0xfe, 0xf2, 0x83, 0xa6, 0x43, 0x36, 0x30, 0x1f, 0xf2, 0xec, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xe3, 0x29, 0x66, 0x97, 0xa3, 0x02, 0x00, 0x00,
}

func (m *Player) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Player) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Player) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Storage.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPlayer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if m.StructsLoad != 0 {
		i = encodeVarintPlayer(dAtA, i, uint64(m.StructsLoad))
		i--
		dAtA[i] = 0x60
	}
	if m.CapacitySecondary != 0 {
		i = encodeVarintPlayer(dAtA, i, uint64(m.CapacitySecondary))
		i--
		dAtA[i] = 0x58
	}
	if m.Capacity != 0 {
		i = encodeVarintPlayer(dAtA, i, uint64(m.Capacity))
		i--
		dAtA[i] = 0x50
	}
	if m.Load != 0 {
		i = encodeVarintPlayer(dAtA, i, uint64(m.Load))
		i--
		dAtA[i] = 0x48
	}
	if len(m.FleetId) > 0 {
		i -= len(m.FleetId)
		copy(dAtA[i:], m.FleetId)
		i = encodeVarintPlayer(dAtA, i, uint64(len(m.FleetId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PlanetId) > 0 {
		i -= len(m.PlanetId)
		copy(dAtA[i:], m.PlanetId)
		i = encodeVarintPlayer(dAtA, i, uint64(len(m.PlanetId)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.PrimaryAddress) > 0 {
		i -= len(m.PrimaryAddress)
		copy(dAtA[i:], m.PrimaryAddress)
		i = encodeVarintPlayer(dAtA, i, uint64(len(m.PrimaryAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPlayer(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SubstationId) > 0 {
		i -= len(m.SubstationId)
		copy(dAtA[i:], m.SubstationId)
		i = encodeVarintPlayer(dAtA, i, uint64(len(m.SubstationId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.GuildId) > 0 {
		i -= len(m.GuildId)
		copy(dAtA[i:], m.GuildId)
		i = encodeVarintPlayer(dAtA, i, uint64(len(m.GuildId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Index != 0 {
		i = encodeVarintPlayer(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintPlayer(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPlayer(dAtA []byte, offset int, v uint64) int {
	offset -= sovPlayer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Player) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovPlayer(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovPlayer(uint64(m.Index))
	}
	l = len(m.GuildId)
	if l > 0 {
		n += 1 + l + sovPlayer(uint64(l))
	}
	l = len(m.SubstationId)
	if l > 0 {
		n += 1 + l + sovPlayer(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPlayer(uint64(l))
	}
	l = len(m.PrimaryAddress)
	if l > 0 {
		n += 1 + l + sovPlayer(uint64(l))
	}
	l = len(m.PlanetId)
	if l > 0 {
		n += 1 + l + sovPlayer(uint64(l))
	}
	l = len(m.FleetId)
	if l > 0 {
		n += 1 + l + sovPlayer(uint64(l))
	}
	if m.Load != 0 {
		n += 1 + sovPlayer(uint64(m.Load))
	}
	if m.Capacity != 0 {
		n += 1 + sovPlayer(uint64(m.Capacity))
	}
	if m.CapacitySecondary != 0 {
		n += 1 + sovPlayer(uint64(m.CapacitySecondary))
	}
	if m.StructsLoad != 0 {
		n += 1 + sovPlayer(uint64(m.StructsLoad))
	}
	l = m.Storage.Size()
	n += 1 + l + sovPlayer(uint64(l))
	return n
}

func sovPlayer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPlayer(x uint64) (n int) {
	return sovPlayer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Player) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlayer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Player: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Player: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuildId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuildId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubstationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubstationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrimaryAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrimaryAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlanetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FleetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlayer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FleetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Load", wireType)
			}
			m.Load = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Load |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capacity", wireType)
			}
			m.Capacity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Capacity |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapacitySecondary", wireType)
			}
			m.CapacitySecondary = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CapacitySecondary |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StructsLoad", wireType)
			}
			m.StructsLoad = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StructsLoad |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Storage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPlayer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPlayer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Storage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlayer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPlayer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPlayer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPlayer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlayer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPlayer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPlayer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPlayer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPlayer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPlayer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPlayer = fmt.Errorf("proto: unexpected end of group")
)
