// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: structs/structs/reactor.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Reactor struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Validator string `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Energy    uint64 `protobuf:"varint,3,opt,name=energy,proto3" json:"energy,omitempty"`
	Load      uint64 `protobuf:"varint,4,opt,name=load,proto3" json:"load,omitempty"`
	Activated bool   `protobuf:"varint,5,opt,name=activated,proto3" json:"activated,omitempty"`
	GuildId   uint64 `protobuf:"varint,6,opt,name=guildId,proto3" json:"guildId,omitempty"`
}

func (m *Reactor) Reset()         { *m = Reactor{} }
func (m *Reactor) String() string { return proto.CompactTextString(m) }
func (*Reactor) ProtoMessage()    {}
func (*Reactor) Descriptor() ([]byte, []int) {
	return fileDescriptor_4de5f586530fedc8, []int{0}
}
func (m *Reactor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Reactor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Reactor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Reactor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reactor.Merge(m, src)
}
func (m *Reactor) XXX_Size() int {
	return m.Size()
}
func (m *Reactor) XXX_DiscardUnknown() {
	xxx_messageInfo_Reactor.DiscardUnknown(m)
}

var xxx_messageInfo_Reactor proto.InternalMessageInfo

func (m *Reactor) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Reactor) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *Reactor) GetEnergy() uint64 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *Reactor) GetLoad() uint64 {
	if m != nil {
		return m.Load
	}
	return 0
}

func (m *Reactor) GetActivated() bool {
	if m != nil {
		return m.Activated
	}
	return false
}

func (m *Reactor) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func init() {
	proto.RegisterType((*Reactor)(nil), "structs.structs.Reactor")
}

func init() { proto.RegisterFile("structs/structs/reactor.proto", fileDescriptor_4de5f586530fedc8) }

var fileDescriptor_4de5f586530fedc8 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe3, 0x10, 0x52, 0xe2, 0x01, 0x24, 0xab, 0x02, 0x53, 0x81, 0x15, 0x31, 0x65, 0xa1,
	0x15, 0x42, 0x62, 0xa7, 0x1b, 0x6b, 0xd8, 0x58, 0x90, 0x89, 0xad, 0xc8, 0x52, 0xe8, 0x55, 0xf6,
	0xb5, 0xa2, 0x6f, 0xc1, 0xc3, 0xc0, 0x3b, 0x30, 0x56, 0x4c, 0x8c, 0x28, 0x79, 0x11, 0x84, 0x9d,
	0xb4, 0xd3, 0xdd, 0xff, 0xf9, 0xf7, 0x2f, 0xdd, 0x4f, 0x2f, 0x1d, 0xda, 0x55, 0x85, 0x6e, 0x36,
	0x4c, 0xab, 0x65, 0x85, 0x60, 0xa7, 0x4b, 0x0b, 0x08, 0xec, 0xa4, 0xc7, 0xd3, 0x7e, 0x4e, 0xce,
	0x2b, 0x70, 0xaf, 0xe0, 0x9e, 0xfd, 0xf3, 0x2c, 0x88, 0xe0, 0x9d, 0x8c, 0x6b, 0xa8, 0x21, 0xf0,
	0xff, 0x2d, 0xd0, 0xab, 0x4f, 0x42, 0x47, 0x65, 0xc8, 0x64, 0xc7, 0x34, 0x36, 0x8a, 0x93, 0x9c,
	0x14, 0x49, 0x19, 0x1b, 0xc5, 0xee, 0x68, 0xb6, 0x96, 0x8d, 0x51, 0x12, 0xc1, 0xf2, 0x38, 0x27,
	0x45, 0x36, 0xe7, 0xdf, 0x1f, 0xd7, 0xe3, 0x3e, 0xf6, 0x5e, 0x29, 0xab, 0x9d, 0x7b, 0x44, 0x6b,
	0x16, 0x75, 0xb9, 0xb7, 0xb2, 0x53, 0x9a, 0xea, 0x85, 0xb6, 0xf5, 0x86, 0x1f, 0xf8, 0xac, 0x5e,
	0x31, 0x46, 0x93, 0x06, 0xa4, 0xe2, 0x89, 0xa7, 0x7e, 0x67, 0x17, 0x34, 0x93, 0x15, 0x9a, 0xb5,
	0x44, 0xad, 0xf8, 0x61, 0x4e, 0x8a, 0xa3, 0x72, 0x0f, 0x18, 0xa7, 0xa3, 0x7a, 0x65, 0x1a, 0xf5,
	0xa0, 0x78, 0xea, 0x3f, 0x0d, 0x72, 0x7e, 0xf3, 0xd5, 0x0a, 0xb2, 0x6d, 0x05, 0xf9, 0x6d, 0x05,
	0x79, 0xef, 0x44, 0xb4, 0xed, 0x44, 0xf4, 0xd3, 0x89, 0xe8, 0xe9, 0x6c, 0xa8, 0xea, 0x6d, 0x57,
	0x1a, 0x6e, 0x96, 0xda, 0xbd, 0xa4, 0xfe, 0xe2, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1,
	0xec, 0x97, 0xac, 0x54, 0x01, 0x00, 0x00,
}

func (m *Reactor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Reactor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Reactor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GuildId != 0 {
		i = encodeVarintReactor(dAtA, i, uint64(m.GuildId))
		i--
		dAtA[i] = 0x30
	}
	if m.Activated {
		i--
		if m.Activated {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Load != 0 {
		i = encodeVarintReactor(dAtA, i, uint64(m.Load))
		i--
		dAtA[i] = 0x20
	}
	if m.Energy != 0 {
		i = encodeVarintReactor(dAtA, i, uint64(m.Energy))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintReactor(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintReactor(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintReactor(dAtA []byte, offset int, v uint64) int {
	offset -= sovReactor(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Reactor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovReactor(uint64(m.Id))
	}
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovReactor(uint64(l))
	}
	if m.Energy != 0 {
		n += 1 + sovReactor(uint64(m.Energy))
	}
	if m.Load != 0 {
		n += 1 + sovReactor(uint64(m.Load))
	}
	if m.Activated {
		n += 2
	}
	if m.GuildId != 0 {
		n += 1 + sovReactor(uint64(m.GuildId))
	}
	return n
}

func sovReactor(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReactor(x uint64) (n int) {
	return sovReactor(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Reactor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReactor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Reactor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Reactor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReactor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReactor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReactor
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReactor
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Energy", wireType)
			}
			m.Energy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReactor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Energy |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Load", wireType)
			}
			m.Load = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReactor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Load |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Activated", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReactor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Activated = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuildId", wireType)
			}
			m.GuildId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReactor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GuildId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReactor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReactor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReactor(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReactor
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReactor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReactor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReactor
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReactor
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReactor
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReactor        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReactor          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReactor = fmt.Errorf("proto: unexpected end of group")
)
